### PR TITLE
Fix #3637 Clicking the 'map'-tab gives an error when no xref attribute has been selected yet

### LINKED ISSUE #3637: Clicking the 'map'-tab gives an error when no xref attribute has been selected yet
## To reproduce:
1. Make a mapping project with at least one xref in it
2. Edit the xref mapping
3. Don't select an attribute yet in the mapping screen, but go the the 'map'-tab

## Expected:
Empty tab is shown or tab is not clickable.

## Actual:
image

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
Added IDs to the script and map tab of the mapping column
Added a JS check that disables the map tab when there are no attributes selected.

This prevents errors when the map tab is trying to load drop down values but there is not attribute selected to get the values from

### CODE REVIEW

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java [hunk 1]
```diff
@@ -60,7 +61,7 @@ public String validateVCF(File vcfFile)
 				logFile.createNewFile();
 			}
 
-			FileWriter fileWriter = new FileWriter(logFile.getAbsoluteFile(), true);
+			FileWriterWithEncoding fileWriter = new FileWriterWithEncoding(logFile.getAbsoluteFile(), "UTF-8", true);
```
Comment (dennishendriksen) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java]: Why not use standard Java IO classes?
BufferedWriter out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("myfile.txt"), "UTF-8"));

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java [hunk 2]
```diff
@@ -90,6 +91,7 @@ public String validateVCF(File vcfFile)
 			bufferedWriter.close();
 
 			scanner.close();
+			errorScanner.close();
```
Comment (dennishendriksen) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java]: Put close calls in finally block such that streams are closed in case an exception occurs.

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java [hunk 3]
```diff
@@ -4,7 +4,6 @@
 
 import java.io.BufferedWriter;
```
Comment (dennishendriksen) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java]: Next time, please put this commit in a separate pull request.

**Comment by dennishendriksen** [comment]
Fix tested successfully.

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java (hunk 3 above)
Comment (Mark-de-Haan) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/cmd/VcfValidator.java]: I thought I did >.<

**Comment by Mark-de-Haan** [comment]
@dennishendriksen Fixed the two pull request on one issue
