### PR TITLE
Fix #6169: Forms only shows first exception message out of n exception messages

### LINKED ISSUE #6169: Forms only shows first exception message out of n exception messages
### How to Reproduce
1. Add a scheduled job
2. Make multiple JSON errors in the parameters field
3. Submit

### Expected behavior
All JSON validation messages are shown.

### Observed behavior
Only the first JSON validation message is shown. (Plugin in the background does show all warnings).

### PR DESCRIPTION
**Pull request by fdlk**
…n messages

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-core-ui/src/main/javascript/modules/react-components/AlertMessage.js [hunk 1]
```diff
@@ -2,7 +2,11 @@ import React from "react";
 import DeepPureRenderMixin from "./mixin/DeepPureRenderMixin";
 import Icon from "./Icon";
 
-var div = React.DOM.div, span = React.DOM.span, button = React.DOM.button;
+var div = React.DOM.div, span = React.DOM.span, button = React.DOM.button, br = React.DOM.br;
+
+function intersperse(arr, sep) {
+    return arr.reduce((a, v) => [...a, v, sep], []).slice(0, -1)
```
Comment (tommydeboer) [inline molgenis-core-ui/src/main/javascript/modules/react-components/AlertMessage.js]: 😮

**Comment by tommydeboer** [comment]
The error messages look like this:

```
&nbsp;Scheduled job changes could not be saved.
[object Object]
[object Object]
```

I've built everything multiple times. I also ran ```webpack-watch.sh``` and double-checked that it refreshed and stuff.

**Comment by fdlk** [comment]
I probably wrecked it last minute. Sorry! Taking a look.
