### PR TITLE
Fix #6575 REST calls with an id that ends with a file extension get swallowed by Spring

### LINKED ISSUE #6575: REST calls with an id that ends with a file extension get swallowed by Spring
### How to Reproduce
Go to dataexplorer
Select StyleSheet
Try to alter StyleSheet

### Expected behavior
I can alter it

### Observed behavior
Error! No logging.

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

File: molgenis-core-ui/src/main/java/org/molgenis/ui/MolgenisWebAppConfig.java [hunk 1]
```diff
@@ -320,7 +324,8 @@ protected void postProcessConfiguration(Configuration config) throws IOException
 	}
 
 	// Override in subclass if you need more freemarker variables
-	protected void addFreemarkerVariables(Map<String, Object> freemarkerVariables)
+	@SuppressWarnings("unused")
+	private void addFreemarkerVariables(Map<String, Object> freemarkerVariables)
```
Comment (dennishendriksen) [inline molgenis-core-ui/src/main/java/org/molgenis/ui/MolgenisWebAppConfig.java]: Overriding is quiet hard now that the method is private ;-)
