### PR TITLE
Fix #5785 When mapping to new table, the new table is not added to the base package when no package is given

### LINKED ISSUE #5785: When mapping to new table, the new table is not added to the base package when no package is given
### How to Reproduce
Map to a table with the name test

### Expected behavior
Error! Specify the package or it succeeds and table base_test is created

### Observed behavior
table test outside of any package is created

### PR DESCRIPTION
**Pull request by marikaris**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/MappingServiceImpl.java [hunk 1]
```diff
@@ -205,6 +216,7 @@ public String applyMappings(MappingTarget mappingTarget, String entityName, bool
 			}
 		}
 
+
```
Comment (Mark-de-Haan) [inline molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/MappingServiceImpl.java]: Run formatting on your file please
