### PR TITLE
Fix #7908 StackOverflowError when moving a package to its child

### LINKED ISSUE #7908: StackOverflowError when moving a package to its child
### How to Reproduce
1. Go to Package in the Data Explorer
1. Add a package _parent_
2. Add a package _child_, with package _parent_ as its parent.
3. Edit package _parent_ and set itss parent to package _child_

### Expected behavior
An error explaining that you can't move packages to its sub-packages.

### Observed behavior
```
Package changes could not be saved.
Handler dispatch failed; nested exception is java.lang.StackOverflowError
```

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [NA] User documentation updated
- [NA] (If you have changed REST API interface) view-swagger.ftl updated
- [NA] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java [hunk 1]
```diff
@@ -42,4 +47,20 @@ private void validatePackageAllowed(Package aPackage) {
   private static void validatePackageName(Package aPackage) {
     NameValidator.validatePackageId(aPackage.getId());
   }
+
+  private static void validatePackageParent(Package aPackage) {
```
Comment (tommydeboer) [inline molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java]: I think you can use  `PackageUtils.contains()` here to check if the current package contains the package you want to set as a parent.

Comment (dennishendriksen) [reply molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java]: Cool, wasn't aware that such a method already existed. As mentioned offline the contains algorithm prunes the children instead of the parent. Lets check outside of this PR if we can merge the algorithms.
