### PR TITLE
Fix #6219: RestControllerV2IT can fail depending on server state befo…

### LINKED ISSUE #6219: RestControllerV2IT can fail depending on server state before the test
### How to Reproduce
Happened on May 31.
```
Failed tests:
  RestControllerV2IT.batchCreate:104 1 expectation failed.
Expected status code <201> but was <400>.

 RestControllerV2IT.batchCreateLocation:126 1 expectation failed.
Expected status code <201> but was <500>.
```

Server-side
```
03:00:38.183 [ajp-bio-8009-exec-8] INFO  o.m.data.rest.v2.RestControllerV2 - Operation failed.
org.molgenis.data.validation.MolgenisValidationException: Duplicate value 'ref55' for unique attribute 'value' from entity 'it_emx_datatypes_TypeTestRefv2'.
```
and
```
03:00:38.579 [ajp-bio-8009-exec-15] ERROR o.m.data.rest.v2.RestControllerV2 - Runtime exception occurred.
java.lang.RuntimeException: Unknown attribute for column name ["Position"]
```

### Expected behavior
Integration tests do not depend on server state, only on server code

### Observed behavior
Tests fail if it_emx_datatypes_TypeTestRefv2 pre-exists and contains row with ID ref55

Workaround is to run the tests again. The teardown cleans up the server.

### PR DESCRIPTION
**Pull request by fdlk**
…re the test

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2IT.java [hunk 1]
```diff
@@ -55,6 +55,13 @@ public void beforeClass()
 
 		adminToken = RestTestUtils.login(adminUserName, adminPassword);
 
+		LOG.info("Clean up test entities if they already exist...");
+		removeEntity(adminToken, "it_emx_datatypes_TypeTestv2");
```
Comment (ConnorStroomberg) [inline molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2IT.java]: maybe move duplicate clean up code to method ?

**Comment by fdlk** [comment]
@ConnorStroomberg  done
