### PR TITLE
Fix #5873: Fileingest does not show "target" anymore

### LINKED ISSUE #5873: Fileingest does not show "target" anymore
### How to Reproduce
create job as per testplan

### Expected behavior
The table with the executed jobs has an header:
'test' import jobs (Target: city)

### Observed behavior
'test' import jobs (Target: )

### PR DESCRIPTION
**Pull request by bartcharbon**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-core-ui/src/main/javascript/modules/react-components/FileIngestPlugin.js [hunk 1]
```diff
@@ -33,7 +33,11 @@ class FileIngestPlugin extends Component {
                     <legend>
                         '{fileIngest.name}' import jobs
                         <span> (Target: <a
-                            href={'/menu/main/dataexplorer?entity=' + fileIngest.entityType.fullName}>{fileIngest.entityType.simpleName}</a>)</span>
+        href = {'/menu/main/dataexplorer?entityId=' +fileIngest.entityType.id} > {fileIngest.entityType.name
+    }</
+        a >
```
Comment (marikaris) [inline molgenis-core-ui/src/main/javascript/modules/react-components/FileIngestPlugin.js]: weird formatting
