### PR TITLE
[Fix] Make request body optional when updating entity.attribute via rest api

### LINKED ISSUE #7942: Update single attribute put/post is rejected if body is empty or null
### How to Reproduce
Send a post to the rest api endpoint 
http://[server]/api/v1/[entity-id]/[attribute-id]
method: PUT or Post
Content-Type: application/json'
With empty request body 

### Expected behavior
The attribute of the referenced entity is cleared / set to null.

### Observed behavior
The request is rejected with the message that the request is not valid, due to missing request body.

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
This allows clearing the attribute value

Fix #7942 

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java [hunk 1]
```diff
@@ -591,6 +592,31 @@ public void testUpdateAttributePut() {
...
+    given()
+        .log()
+        .all()
+        .header(X_MOLGENIS_TOKEN, testUserToken)
+        .get(API_V1 + "V1_API_TypeTestAPIV1/1/xstringnillable")
+        .then()
+        .log()
+        .all()
+        .statusCode(OKE)
+        .body("xstringnillable", nullValue());
```
Comment (fdlk) [inline molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java]: should be before the then I think?

Comment (ConnorStroomberg) [reply molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java]: ?? no ? send out the 'get' to check if update was succes, then when the get returns check the result

**Comment by fdlk** [comment]
@ConnorStroomberg and I took a look and we think you can already upload a request body containing
`null`
