### PR TITLE
Fix #7630 Metadata manager cascade delete support

### LINKED ISSUE #7630: Metadata manager cannot enable/disable attribute cascading delete
### How to Reproduce
- As superuser navigate to the 'metadata manager' plugin in menu 'Data Integration'
- Select entity type 'Package' in the entity type drop-down
- Select attribute 'Parent'

### Expected behavior
- I see a enabled 'Cascade delete' checkbox

### Observed behavior
- No way to see or update 'Cascade delete' status through metadata manager

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [NA] User documentation updated
- [NA] (If you have changed REST API interface) view-swagger.ftl updated
- [NA] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue [hunk 1]
```diff
@@ -117,6 +117,13 @@
             </div>
           </div>
 
+          <div v-if="isReferenceType" class="form-group row">
+            <label class="col-3 col-form-label text-muted">{{ 'attribute-edit-form-cascade-delete-label' | i18n }}</label>
```
Comment (bartcharbon) [inline molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue]: Please add default "en" and "nl" values for this key
