### PR TITLE
Fix #7814 Metadata manager reference to no-reference type update

### LINKED ISSUE #7814: Metadata manager attribute reference to no-reference type update
### How to Reproduce
- load typetest
- change "xref" attribute to String
- save changes

### Expected behavior
- success

### Observed behavior
- error because the refEntity field for the attribute is not empty (and should be for a string), however the "refEntity" field gets hidden for strings, so I have to empty the refEnity field before changing the datatype

### Desired behaviour (I think)
The refEntity field should be cleared "onSave". 
Clearing it "onChange" would be annoying when you change datatype by accident.

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- (n.a.) User documentation updated
- (n.a.) (If you have changed REST API interface) view-swagger.ftl updated
- (n.a.) Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-metadata-manager/src/main/frontend/src/store/mutations.js [hunk 1]
```diff
@@ -144,6 +165,7 @@ export default {
       }
     }
     state.editorEntityType.attributes[index][key] = update.value
+    console.log(state.editorEntityType.attributes[index])
```
Comment (tommydeboer) [inline molgenis-metadata-manager/src/main/frontend/src/store/mutations.js]: Forgot to remove?
