### PR TITLE
Fix #6360 Separate sign-up form and OIDC settings

### LINKED ISSUE #6360: Google sign-in only works as long as user signup is enabled and moderation is disabled
### How to Reproduce
Open app settings, enable google sign-in

### Expected behavior
* I can enable google sign-up in combination with moderation
* Accounts that have signed up using google can still log in even if I disable signup

### Observed behavior
* I can only allow google sign-in in combination with signup enabled and moderation disabled

### PR DESCRIPTION
**Pull request by tommydeboer**
_Note_: validation expression on the authentication settings doesn't work yet because of the issues with validation expressions.

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] Migration step added in case of breaking change
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data-migrate/src/main/resources/step46-disableInactiveOidcClients.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
+DO $$
+DECLARE
+    settings public."sys_set_auth#98c4c015"%ROWTYPE;
```
Comment (fdlk) [inline molgenis-data-migrate/src/main/resources/step46-disableInactiveOidcClients.sql:3]: help!

**Review by fdlk — CHANGES_REQUESTED** [review]
Missing source code for Step46DisableInactiveOidcClients

**Review by fdlk — APPROVED** [review]
