### PR TITLE
Fix #8230: Usernames are not checked for spaces

### LINKED ISSUE #8230: Usernames are not checked for spaces
### How to Reproduce
Add space in front of username when creating a user.

### Expected behavior
Username is checked for spaces and user can not be created because of invalid input (interface shows a clear error message)

### Observed behavior
User is created, but unable to login

### PR DESCRIPTION
**Pull request by bartcharbon**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [NA] Code unit/integration/system tested
- [NA] User documentation updated
- [NA] (If you have changed REST API interface) view-swagger.ftl updated
- [NA] Test plan template updated
- [x] Clean commits
- [NA] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserMetadata.java [hunk 1]
```diff
@@ -75,7 +75,8 @@ public void init() {
         .setLabel("Username")
         .setUnique(true)
         .setNillable(false)
-        .setReadOnly(true);
+        .setReadOnly(true)
+        .setValidationExpression("$('" + USERNAME + "').matches(/^[\\S].+[\\S]$/).value()");
```
Comment (tommydeboer) [inline molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserMetadata.java]: This pattern does allow spaces in the middle of the username. Should that be possible?
