### PR TITLE
Fix #5536 Changing the datatype of xstring (TypeTest) to int results in wrong error message

### LINKED ISSUE #5536: Changing the datatype of xstring (TypeTest) to int results in wrong error message
#### Reproduce
LOAD: TypeTest
In the Attribute table, change the datatype of xstring (TypeTest) to int

#### Expected
Error! Value [xxx] of this entity attribute is not of type [INT or LONG].

#### Observed
exclamation-sign Attribute changes could not be saved. NumberFormatException For input string: "xstring"

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [x] Unit tests

### CODE REVIEW

File: molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java [hunk 1]
```diff
@@ -190,7 +190,9 @@ void validateDefaultValue(Attribute attr)
 			}
 			catch (NumberFormatException e)
 			{
-				throw new MolgenisDataException(format("%s %s", e.getClass().getSimpleName(), e.getMessage()));
+				throw new MolgenisValidationException(new ConstraintViolation(
+						format("Invalid default value [%s] for data type [%s]", value, attr.getDataType())
```
Comment (Mark-de-Haan) [inline molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java]: Default value has nothing to do with it right?
