### PR TITLE
Fix #8797: OpenID connect redirect_uri sometimes doesn't take X-Forwarded-* headers into account

### LINKED ISSUE #8797: OpenID connect redirect_uri sometimes doesn't take X-Forwarded-* headers into account
### How to Reproduce
In short: try to use OpenID Connect behind a proxy.
It will fail because the redirect_uri is incorrect.

More detailed:
Start server on localhost (or on the kubernetes cluster).
Configure an OIDC client
Set authentication settings: allow signup, no moderation, use the OIDC client

Send a curl with forward header to the OIDC authorization
```
curl --verbose -H "X-Forwarded-Proto: https" -H "X-Forwarded-Host: oidc-test.example.org" http://localhost/oauth2/authorization/<oidc client>
```
(Or on the cluster, just open the URL in the browser)
Examine the redirect_uri in the Location header.

### Expected behavior
The redirect_uri is `https://oidc-test.example.org/oauth2/authorization/<oidc client>` (or on the cluster, the server URL)

### Observed behavior
*sometimes* the redirect_uri is `http://localhost/oauth2/authorization/<oidc client>` (on localhost) or
`http://oidc-test-molgenis:8080/login/oauth2/code/<oidc client>` (on cluster)

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] Migration step added in case of breaking change
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-security/src/main/java/org/molgenis/security/WebAppSecurityInitializer.java [hunk 1]
```diff
@@ -1,5 +1,23 @@
...
+public class WebAppSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
 
-public class WebAppSecurityInitializer extends AbstractSecurityWebApplicationInitializer {}
+  @Override
+  protected void beforeSpringSecurityFilterChain(ServletContext servletContext) {
+    // add filters
+    Dynamic forwardedHeaderFilter =
+        servletContext.addFilter("forwardedHeaderFilter", ForwardedHeaderFilter.class);
+    forwardedHeaderFilter.setAsyncSupported(true);
+    forwardedHeaderFilter.addMappingForUrlPatterns(EnumSet.of(REQUEST, FORWARD, ASYNC), false, "*");
```
Comment (dennishendriksen) [inline molgenis-security/src/main/java/org/molgenis/security/WebAppSecurityInitializer.java]: Why did you add 'FORWARD'?

Comment (fdlk) [reply molgenis-security/src/main/java/org/molgenis/security/WebAppSecurityInitializer.java]: Oops, that's a leftover from previous attempt to fix it. I noticed the filter wasn't getting executed and thought perhaps the inner workings of the OIDC filter included a forward request.

I just now checked how spring boot registers the filter: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.java

They use request, async, error. So forward not needed, removing it.
Shall we add error to match what spring boot does?

Comment (dennishendriksen) [reply molgenis-security/src/main/java/org/molgenis/security/WebAppSecurityInitializer.java]: Good idea.
