### PR TITLE
Port Fix #5084 to 2.0 + bugfixes

### LINKED ISSUE #5084: Mapping service cannot handle self-references
#### Reproduce

1. Upload the LDAP import model: 
https://drive.google.com/open?id=0B8iNw4kI1MA2dEVvRmZrZUwwU0U
2. Upload the new (target) model: 
https://drive.google.com/open?id=0B8iNw4kI1MA2UTlpZS01a3JqZmM
3. Upload the LDAP data (CSV files): 

- https://drive.google.com/open?id=0B8iNw4kI1MA2SlRuSVdvdTNCVG8 (ldap_contactInformation.csv) 
- https://drive.google.com/open?id=0B8iNw4kI1MA2QkcySTBRWjJDYjQ (ldap_biobankNetwork.csv)

4.Create a new mapping project for "networks" and use eu_bbmri_eric_networks as target entity and ldap_biobankNetwork as source entity. 

5.Map all attributes, the problem occurs with the network (mref) attribute

NOTE: You need to upload ldap_contactInformation.csv because ldap_biobankNetwork refers to this entity. When mapping this reference attribute, you can just use empty values for now.
The problem occurs on Molgenis version 1.21.1

#### Expected
Mapped self-reference attribute "network"

#### Observed
Self-reference attribute cannot be mapped because the target entity does contain the required data yet.

### LINKED ISSUE #5147: Creating a new Integrated dataset will fail due to typing errors
### Reproduce
Import TypeTest
Create a mapping project mapping TypeTest to TypeTest
Run 'Create Integrated Dataset'

### Expected
The two are mapped

### Observed
Dataconversion errors:
Attribute [value] value is of type [DynamicEntity] instead of [String]
Attribute [xbool] value is of type [Boolean] instead of [String]

etc..

### LINKED ISSUE #5152: Attribute 'sourceAttributeMetaDatas' of entity 'AttributeMapping' cannot have more than 255 characters
#### Reproduce
1. Upload this target model: https://drive.google.com/open?id=0B8iNw4kI1MA2NzRRNTRqeWNUa2c
2. Upload this source model: https://drive.google.com/open?id=0B8iNw4kI1MA2bXhlTmwyeWgtbU0
3. Upload this CSV file:
https://drive.google.com/open?id=0B8iNw4kI1MA2Rl9TNFhvVGd6X2c
4. Create mapping project: 
target = eu_bbmri_eric_collections
source = ldap_collection
5. Try to map the materials attribute (mref) with these source attributes (booleans):
-materialStoredDNA'
-materialStoredPlasma
-materialStoredSerum
-materialStoredUrine
-materialStoredSaliva
-materialStoredFaeces
-materialStoredOther
-materialStoredRNA
-materialStoredBlood
-materialStoredImmortalizedCL
-materialStoredIsolatedPathogen
-materialStoredTissueFrozen
-materialStoredTissueFFPE
6. Add algorithm and save the mapping:

materials = []

if ($('materialStoredDNA').value() === true){
    materials.push("DNA");
}else if($('materialStoredPlasma').value() === true){
    materials.push("PLASMA");
}else if($('materialStoredSerum').value() === true){
    materials.push("SERUM");
} else if($('materialStoredUrine').value() === true){
    materials.push("URINE");
} else if($('materialStoredSaliva').value() ===true){
    materials.push("SALIVA");
} else if($('materialStoredFaeces').value() ===true){
    materials.push("FAECES");
}else if($('materialStoredOther').value() ===true){
    materials.push("OTHER");
}else if($('materialStoredRNA').value() ===true){
    materials.push("RNA");
}else if($('materialStoredBlood').value() ===true){
    materials.push("BLOOD");
}else if($('materialStoredImmortalizedCL').value() ===true){
    materials.push("CELL_LINES");
}else if($('materialStoredIsolatedPathogen').value() ===true){
   materials.push("PATHOGEN");
}else if($('materialStoredTissueFrozen').value() ===true){
    materials.push("TISSUE_FROZEN");
}else if($('materialStoredTissueFFPE').value() ===true){
    materials.push("TISSUE_PARAFFIN_EMBEDDED");
}else{
    materials.push("NAV");
}
materials;

#### Expected
Mapped attribute (from booleans to mref).

#### Observed
Error! An error occurred. Please contact the administrator.
Message:Invalid string value 'materialStoredDNA,materialStoredPlasma,materialStoredSerum,materialStoredUrine,materialStoredSaliva,materialStoredFaeces,materialStoredOther,materialStoredRNA,materialStoredBlood,materialStoredImmortalizedCL,materialStoredIsolatedPathogen,materialStoredTissueFrozen,materialStoredTissueFFPE' for attribute 'sourceAttributeMetaDatas' of entity 'AttributeMapping'.Value must be less than or equal to 255 characters

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
### Checklist
- [x] Unit tests

### Bugfixes
- Fix #5147 Creating a new Integrated dataset will fail due to typing errors
- Fix #5152 Attribute 'sourceAttributeMetaDatas' of entity 'AttributeMapping' cannot have more than 255 characters

### CODE REVIEW

File: molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/AlgorithmServiceImpl.java [hunk 1]
```diff
@@ -160,19 +160,24 @@ private Object convert(Object value, AttributeMetaData attributeMetaData)
...
-					convertedValue = Context.jsToJava(value, Date.class);
+					convertedValue = jsToJava(value, Date.class);
+					break;
+				case BOOL:
+					convertedValue = toBoolean(value);
 					break;
 				case INT:
-					// Round it up or down to the nearest integer value
-					convertedValue = Math.round(Double.parseDouble(Context.toString(value)));
+					convertedValue = parseInt(Context.toString(value));
```
Comment (fdlk) [inline molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/AlgorithmServiceImpl.java]: That's something different, no?

File: molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/MappingServiceImpl.java [hunk 2]
```diff
@@ -157,91 +154,129 @@ public MappingProject getMappingProject(String identifier)
...
-		List<Entity> mappedEntities = Lists.newArrayList();
-		while (sourceEntities.hasNext())
-		{
-			Entity sourceEntity = sourceEntities.next();
-			Entity mappedEntity = applyMappingToEntity(sourceMapping, sourceEntity, targetMetaData,
-					sourceMapping.getSourceEntityMetaData(), targetRepo);
-			mappedEntities.add(mappedEntity);
-
-			if (mappedEntities.size() == BATCH_SIZE || !sourceEntities.hasNext())
+		sourceRepo.iterator().forEachRemaining(sourceEntity -> {
```
Comment (fdlk) [inline molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/MappingServiceImpl.java]: A TODO item maybe but sourceRepo.iterator() is hopelessly inefficient for large source repositories. forEachBatched is the method you need.

File: molgenis-data-mapper/src/test/java/org/molgenis/data/mapper/service/impl/MappingServiceImplTest.java [hunk 3]
```diff
@@ -345,13 +343,13 @@ public boolean matches(Object obj)
...
 		// apply mapping again
 		String generatedEntityName = mappingService
-				.applyMappings(project.getMappingTarget(TARGET_HOP_ENTITY), entityName);
+				.applyMappings(project.getMappingTarget(TARGET_HOP_ENTITY), entityName, true);
 		assertEquals(generatedEntityName, entityName);
 
-		ArgumentCaptor<Stream<Entity>> streamCaptor = forClass((Class) Stream.class);
-		verify(addEntityRepo).add(streamCaptor.capture());
+		ArgumentCaptor<Entity> entityCaptor = forClass((Class) Entity.class);
+		verify(addEntityRepo, times(4)).add(entityCaptor.capture());
```
Comment (fdlk) [inline molgenis-data-mapper/src/test/java/org/molgenis/data/mapper/service/impl/MappingServiceImplTest.java]: I think you can do four verifies and no longer need the entityCaptor:
```
for(Entity e: expectedEntities) {
  verify(addEntityRepo).add(e)
}
```
