### PR TITLE
Fix #4598 add *.vcf.zip support

### LINKED ISSUE #4598: Import of ZIP/TAR.GZ compressed VCF is not possible
It is not possible to import a zipped (.vcf.zip) VCF. The error thrown:
```
Error! Your import failed:
Can not import file. No suitable importer found
```
Importing a gzipped TAR (.vcf.tar.gz) does not work either. The error thrown:
```
Error! Your import failed:
Unknown extension for file 'myfile.tar.gz'
```
NOTE: Just gzipping the file does work! the extension becomes ".vcf.gz" in that case.

### PR DESCRIPTION
**Pull request by QiaoN**
This change support the file format .vcf.zip (one file in zip only). Which means a zipped vcf file will be accepted. Before this fix the .vcf.zip file will cause import failed.

### CODE REVIEW

**Comment by fdlk** [comment]
Add to whitelist

**Comment by fdlk** [comment]
Hi! Is there an issue with the pull request that caused you to close it? Cause quick code inspection looked good to me.

**Comment by fdlk** [comment]
add to whitelist

**Comment by QiaoN** [comment]
@fdlk Sorry, I accidentally close the pull request. It is fine!

File: molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfReaderFactoryImpl.java [hunk 1]
```diff
@@ -41,6 +44,13 @@ public VcfReader get()
 			if (file.getName().endsWith(".gz"))
 			{
 				inputStream = new GZIPInputStream(inputStream);
+			} 
+			else if (file.getName().endsWith(".zip"))
+			{
+				   ZipFile zipFile = new ZipFile(file.getPath());
+				   Enumeration<? extends ZipEntry> e = zipFile.entries();
+				   ZipEntry entry = (ZipEntry) e.nextElement(); // your only file
```
Comment (fdlk) [inline molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfReaderFactoryImpl.java]: Some OS-es add system-specific entries to a zipfile when you create them from the finder / explorer.
Could you make it so that it imports the first entry with extension .vcf and explains why it fails if no such entry is found?

Comment (QiaoN) [inline molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfReaderFactoryImpl.java]: No problem to fix this part. Will push the change soon if needed.
But one concert is that the original fix was focus on format "*.vcf.zip" which mean directly zip original vcf file. For the folder contain vcf file then zip, the extension will be "*.zip". That will be conflicted with csv reader implementation as importWizard can not call the right reader.
Please let me know if I still need to push the change or not.

Comment (fdlk) [inline molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfReaderFactoryImpl.java]: @QiaoN Ah yes, I had indeed been thinking of zipping a folder.
