### PR TITLE
fix #3655: The SnpEff annotator contains a field that fails with larg…

### LINKED ISSUE #3655: The SnpEff annotator contains a field that fails with large inserts or deletes
The SnpEff annotator contains a field that fails with large inserts or deletes:
DefaultAttributeMetaData HGVS_c = new DefaultAttributeMetaData(HGVS_C, STRING);

This should be TEXT.

### PR DESCRIPTION
**Pull request by bartcharbon**
…e inserts or deletes

### CODE REVIEW

**Comment by bartcharbon** [comment]
Also the new Eclipse formatter was applied to this class

**Comment by Mark-de-Haan** [comment]
@bartcharbon Conflicts with master

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/entity/impl/SnpEffAnnotator.java [hunk 1]
```diff
@@ -370,42 +368,43 @@ else if (ann_field[2].startsWith("NMD="))
...
 
 			DefaultAttributeMetaData rank_total = new DefaultAttributeMetaData(RANK_TOTAL, STRING);
-			rank_total
-					.setDescription("Exon or Intron rank / total number of exons or introns(source:http://snpeff.sourceforge.net)");
+			rank_total.setDescription(
+					"Exon or Intron rank / total number of exons or introns(source:http://snpeff.sourceforge.net)");
 			attributes.add(rank_total);
 
-			DefaultAttributeMetaData HGVS_c = new DefaultAttributeMetaData(HGVS_C, STRING);
+			DefaultAttributeMetaData HGVS_c = new DefaultAttributeMetaData(HGVS_C, TEXT);
```
Comment (fdlk) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/entity/impl/SnpEffAnnotator.java]: And this is where it happens, right?
