### PR TITLE
fix #5234 snpeff does not work anymore, error about the created EFFEC…

### LINKED ISSUE #5234: snpeff does not work anymore, error about the created EFFECTS entity
#### Reproduce
run snpeff from the web interface

#### Expected
great succes

#### Observed
Error! Qualified entity name [entity] not equal to entity package name [package] underscore entity name [entity]

### PR DESCRIPTION
**Pull request by bartcharbon**
#### Checklist
- [x] Unit tests
- [ ] Updated testplan

…TS entity

### CODE REVIEW

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/core/entity/impl/snpeff/SnpEffRunner.java [hunk 1]
```diff
@@ -331,8 +331,7 @@ public EntityMetaData getTargetEntityMetaData(EntityMetaData sourceEMD)
 	{
 		EntityMetaData emd = entityMetaDataFactory.create()
 				.setSimpleName(sourceEMD.getSimpleName() + ENTITY_NAME_SUFFIX).setPackage(sourceEMD.getPackage());
-		String sourcePackage = emd.getPackage() != null ? emd.getPackage().getName() : "SnpEff";
-		emd.setName(sourcePackage + "_" + emd.getSimpleName());
+		emd.setPackage(sourceEMD.getPackage());
```
Comment (fdlk) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/core/entity/impl/snpeff/SnpEffRunner.java]: package already gets set on line 333
(Got to love those fluent interfaces :) )

**Comment by fdlk** [comment]
Ran into #5241 , otherwise looks fine so if you change the line let's merge.
