### PR TITLE
Fix #6052 Apps create/edit buttons malfunction if modal was closed by…

### LINKED ISSUE #6052: Apps create/edit buttons malfunction if modal was closed by clicking next to it
### How to Reproduce
Start creating an app but do not finish, instead close the dialog by clicking next to it.
Than click the create button again.

### Expected behavior
- I get an empty form

### Observed behavior
- the values I filled out the first time are still there

The same occurs when clicking the edit button of a different app, so:
- click create, call the app "pietje", click next to the modal
- click the edit button of a different app -> this form now shows the dialog with "name:pietje"

### PR DESCRIPTION
**Pull request by dennishendriksen**
… clicking next to it

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-apps/src/main/resources/js/apps.js [hunk 1]
```diff
@@ -10,7 +10,7 @@
                 onSubmitSuccess: function () {
                     window.location = molgenis.contextUrl;
                 }
-            }), $('#form-modal-container')[0]).setState({showModal: true});
+            }), $('<div>')[0]);
```
Comment (ConnorStroomberg) [inline molgenis-apps/src/main/resources/js/apps.js]: this seems very brittle to me, could you explain why this fixes the issue ?

Comment (dennishendriksen) [inline molgenis-apps/src/main/resources/js/apps.js]: The React component is rendered in a detached DOM element which causes the component to be recreated on every button select. The same strategy is used in the user manager and scripts plugin.
