### PR TITLE
[1.11] Fix #3878 MySqlRepository returns entities out of order; Fix #3887 When clicking the dropdown in the settingsscreen I get a error

### LINKED ISSUE #3878: MySqlRepository returns entities out of order
```Iterable<Entity> MySqlRepository.findAll(Iterable<Object> ids)``` returns entities out of order. This is unexpected, the desired behavior is that the returned Iterable has the same order as the Iterable of ids.

### LINKED ISSUE #3887: When clicking the dropdown in the settingsscreen I get a error
screen shot 2015-10-13 at 14 54 35

### PR DESCRIPTION
**Pull request by fdlk**
Alternative solution that does not run into the group_concat / order by bug.

### CODE REVIEW

File: molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java [hunk 1]
```diff
@@ -678,7 +678,19 @@ public Entity findOne(Object id)
 	public Iterable<Entity> findAll(Iterable<Object> ids)
 	{
 		if (ids == null) return Collections.emptyList();
-		return findAll(new QueryImpl().in(getEntityMetaData().getIdAttribute().getName(), ids));
+		Query inQuery = new QueryImpl().in(getEntityMetaData().getIdAttribute().getName(), ids);
+		Map<Object, Entity> index = uniqueIndex(newArrayList(findAll(inQuery)), Entity::getIdValue);
```
Comment (fdlk) [inline molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java]: This means the complete set of results gets cached in memory. On the other hand I'd expect that a query for specific ids is limited to manageable batches of rows. Could add batching here to make sure. What do you guys think?

File: molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java [hunk 2]
```diff
@@ -678,7 +678,19 @@ public Entity findOne(Object id)
...
+		return Iterables.filter(Iterables.transform(ids, id -> lookup(index, id)), x -> x != null);
+	}
+
+	public Entity lookup(Map<Object, Entity> index, Object id)
+	{
+		Entity result = index.get(id);
+		if (result == null)
+		{
+			LOG.warn("Couldn't find {} for id {}.", getName(), id);
```
Comment (fdlk) [inline molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java]: I ran into an issue here where the type of the ID that gets sent to the query method is different from the java type returned by the getIdValue of the entity. I think that it was a bug that ElasticSearch sent String representations of int IDs to the findAll method. But perhaps it happens elsewhere as well.

File: molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java [hunk 3]
```diff
@@ -956,32 +968,7 @@ protected String getSortSql(Query q, List<Object> parameters)
...
-					// define order of returned rows
-					sortSql = new StringBuilder("ORDER BY FIELD(").append("this.").append('`')
-							.append(queryRule.getField()).append('`').append(",").append(fieldIds).append(")");
-
-					// use prepared statements for the values
-					parameters.addAll(StreamSupport.stream(values.spliterator(), false).map(value -> value.toString())
-							.collect(Collectors.toList()));
-				}
-			}
-		}
```
Comment (fdlk) [inline molgenis-data-mysql/src/main/java/org/molgenis/data/mysql/MysqlRepository.java]: This is the old solution, it specifies the order of the result rows in an ORDER BY FIELD clause. In MySQL 5.1 it runs into a bug where the collected MREF IDs get truncated if you add an ORDER BY.

File: molgenis-data/src/main/java/org/molgenis/data/Repository.java [hunk 4]
```diff
@@ -45,9 +45,9 @@
 	Entity findOne(Object id);
 
 	/**
-	 * find entities based on a stream of ids.
+	 * find entities based on a stream of ids
 	 * 
-	 * @return (empty) Iterable where the order of entities matches the order of ids, never null
+	 * @return (empty) Iterable, never null
```
Comment (fdlk) [inline molgenis-data/src/main/java/org/molgenis/data/Repository.java]: How so never null? What's supposed to happen if one of the rows isn't found in the repository?

File: molgenis-data/src/main/java/org/molgenis/data/support/AbstractRepository.java [hunk 5]
```diff
@@ -1,18 +1,35 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import org.springframework.transaction.annotation.Transactional;
 
 /**
  * Base class for repositories. Subclasses can override supported methods
  */
 public abstract class AbstractRepository implements Repository
 {
+	private static final int FIND_ALL_BATCH_SIZE = 1000;
```
Comment (fdlk) [inline molgenis-data/src/main/java/org/molgenis/data/support/AbstractRepository.java]: Picked the same batch size as the elastic search iterator.

**Comment by fdlk** [comment]
Must still go to master
