### PR TITLE
Fix #7502: When I reload questionnaire page, the answers are gone

### LINKED ISSUE #7502: When I reload questionnaire page, the answers are gone
### How to Reproduce
Open questionnaire, fill in some answers, and reload the page or switch language.

### Expected behavior
Answers appear on reloaded page

### Observed behavior
Answers are gone

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [x] Functionality works & meets specifications
- [ ] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-questionnaires/src/main/frontend/src/store/getters.js [hunk 1]
```diff
@@ -49,12 +49,7 @@ const isVisible = (field: ChapterField, formData: Object) => {
   try {
     visible = field.visible(formData)
   } catch (e) {
-    console.error(`Error in getters, during evaluation of function 'visible' for field ${field.id}.
-      Where visible expression is: 
-        '${field.visible.toString()}'
-      And formData is: 
-        '${JSON.stringify(formData)}'
-      The default value of visible is set to false`, e)
+    console.log(`Setting ${field.id}.visible to false.`)
```
Comment (dennishendriksen) [inline molgenis-questionnaires/src/main/frontend/src/store/getters.js]: @sidohaakma is wondering why this is a console.log instead of a console.error

Comment (fdlk) [reply molgenis-questionnaires/src/main/frontend/src/store/getters.js]: When you start up the application with the vuex debugger open, you get about fifty of these messages which is overly disturbing. Therefore I toned down the red screaming messages a bit.

Comment (dennishendriksen) [reply molgenis-questionnaires/src/main/frontend/src/store/getters.js]: ok, but the question remains: why log instead of error?

Comment (fdlk) [reply molgenis-questionnaires/src/main/frontend/src/store/getters.js]: Because it is not always an error. Talked with @sidohaakma and we'll turn it into a log.warn.

**Comment by tommydeboer** [comment]
There are other issues with the TestQuestionnaire! Some attributes don't show up because they aren't in a compound.
