### PR TITLE
Fix #5988 No error when validating mapping of 'null' values to not nillable mref

### LINKED ISSUE #5988: No error when validating mapping of 'null' values to not nillable mref
### How to Reproduce
Use 3.0 RD connect
Load RD connect data in drive folder: rd connect marieke and mariska. In order of read me in that directory (at molgenis80 28-03-2017)
Alter mapping of UCL disease to: 
`var prefix = 'urn:miriam:orphanet:Orphanet_'
var code = $('Diagnosis_Orphanet_Code').value()
[prefix+code]`
Click validate expression

### Expected behavior
Validation fails because there are empty cells in source

### Observed behavior
Validation succeeds but mapping fails with: 
ClassCastException: null
No stacktrace

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
#### Checklist
- [ ] Functionality works & meets specifications
- [x] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

[test_5988.xlsx](https://github.com/molgenis/molgenis/files/915781/test_5988.xlsx)

### CODE REVIEW

File: molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/AlgorithmServiceImpl.java [hunk 1]
```diff
@@ -101,23 +101,27 @@ public void autoGenerateAlgorithm(EntityType sourceEntityType, EntityType target
...
-		return Iterables.transform(sourceEntities, entity ->
+		return stream(sourceEntities.spliterator(), false).map(entity ->
 		{
 			AlgorithmEvaluation algorithmResult = new AlgorithmEvaluation(entity);
-
 			Object derivedValue;
+
 			try
 			{
 				Object result = jsMagmaScriptEvaluator.eval(algorithm, entity);
```
Comment (ConnorStroomberg) [inline molgenis-data-mapper/src/main/java/org/molgenis/data/mapper/service/impl/AlgorithmServiceImpl.java]: could you not check for null / empty instead of catching the exception ? If we expect null it does not seem like a exceptional state.

**Comment by ConnorStroomberg** [comment]
look good, will merge when tests have run succesfully
