### PR TITLE
Fix #6967 Molgenis does not run on mac os version 'high sierra'.

### LINKED ISSUE #6967: MenuManagerServiceImpl bean not found during bootstrap on mac os version 'high sierra'
### How to Reproduce
- Install high sierra on a apple mac
- checkout and build molgenis master
- run molgenis

### Expected behavior
- molgenis bootstraps and starts 

### Observed behavior
- startup fails with error message indicating 'MenuManagerServiceImpl' bean can not be found, but is needed in 'AppDbSettings'

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
Fix #6967 Molgenis does not run on mac os version 'high sierra'.

I suspect due to changes in the high sierra file system (faster) the 'AppDbSettings' is now called before the 'MenuManagerServiceImpl' is created, 'AppDbSettings' needs 'MenuManagerServiceImpl'.

Adding the @Component annotation makes it possible to wire 'MenuManagerServiceImpl' on 'AppDbSettings' instantiation.

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

**Comment by fdlk** [comment]
I'll upgrade tonight and test it tomorrow.

File: molgenis-core-ui/src/main/java/org/molgenis/ui/menumanager/MenuManagerServiceImpl.java [hunk 1]
```diff
@@ -24,6 +25,7 @@
 import static java.util.Objects.requireNonNull;
 import static java.util.stream.Collectors.toList;
 
+@Component
```
Comment (fdlk) [inline molgenis-core-ui/src/main/java/org/molgenis/ui/menumanager/MenuManagerServiceImpl.java]: I think you can now remove the explicit java config @Bean method in MolgenisWebAppConfig

**Comment by sidohaakma** [comment]
Deleted MenuManagerService and DataService from MolgenisWebappConfig to cleanup the code some more.
