### PR TITLE
Fix #9304 Log script output if the script fails

### LINKED ISSUE #9304: Scripts don't show output if there is an error
### How to Reproduce
1. Go to the Scripts plugin
2. Add the following Python script:
```python
print("show me")
raise ValueError()
```
3. Save and run it

### Expected behavior
The script fails but I can still inspect the output to see what has happened until the error occurred.

### Observed behavior
Only the error is logged:
```
09:49:34.957 CEST - Failed. Error running [/usr/local/Cellar/tomcat/9.0.35/libexec/temp/13105102389242304189.py].Traceback (most recent call last):
  File "/usr/local/Cellar/tomcat/9.0.35/libexec/temp/13105102389242304189.py", line 3, in <module>
    raise ValueError()
ValueError
```

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] Migration step added in case of breaking change
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [ ] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-python/src/main/java/org/molgenis/python/PythonStreamHandler.java [hunk 1]
```diff
@@ -25,9 +26,9 @@ public void start() {
   public void run() {
     try {
       BufferedReader br = new BufferedReader(new InputStreamReader(in, UTF_8));
-      String line = null;
+      String line;
       while ((line = br.readLine()) != null) {
-        outputHandler.outputReceived(line);
+        outputHandler.append(line + "\n");
```
Comment (fdlk) [inline molgenis-python/src/main/java/org/molgenis/python/PythonStreamHandler.java:31]: This one is nice and streaming!

File: molgenis-python/src/main/java/org/molgenis/python/PythonScriptRunner.java [hunk 2]
```diff
@@ -31,8 +32,15 @@ public boolean hasFileOutput(Script script) {
   @Override
   public String runScript(Script script, Map<String, Object> parameters) {
     String generatedScript = ScriptUtils.generateScript(script, parameters);
-    StringPythonOutputHandler handler = new StringPythonOutputHandler();
+    var handler = new ScriptOutputHandler();
```
Comment (fdlk) [inline molgenis-python/src/main/java/org/molgenis/python/PythonScriptRunner.java:35]: Too bad ScriptRunner interface is not streaming, it really should send progress messages and append to log. 🐛

**Review by fdlk — APPROVED** [review]
Nice improvements!
Hungry-little-caterpillar-me is still eager for the script runner to stream output as it gets created.
