### PR TITLE
Fix #7448 Can not upload bio-bank data model

### LINKED ISSUE #7448: Can not upload bio-bank data model
### How to Reproduce
Login as super user
Upload the [bio-bank model emx ](https://drive.google.com/drive/folders/189aUFTVm0zARjFTXppr6OIIFzRZYzyMJ)
click next
click next

### Expected behavior
The next step in the uploader process is shown

### Observed behavior
screen shot 2018-06-14 at 11 15 17

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java [hunk 1]
```diff
@@ -149,7 +149,7 @@ private String validateInput(File file, ImportWizard wizard, BindingResult resul
 		wizard.setEntitiesInDefaultPackage(entitiesInDefaultPackage);
 
 		Map<String, String> packageSelection = getPackageSelection(packages);
-		if (packageSelection.isEmpty())
+		if (!entitiesInDefaultPackage.isEmpty() && packageSelection.isEmpty())
```
Comment (ConnorStroomberg) [inline molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java]: Does this new branch need a test case ?
