### PR TITLE
Fix #4080 Update active session authentication roles

### LINKED ISSUE #4080: Updating permissions for users requires them to log out and in
### To reproduce:
1. Make a new user
2. Log in with that user (don't log out!)
3. In a separate session as an admin, give the user permissions for the data explorer
4. As the user, refresh the page.
### Expected:

The user can now see the Data Explorer.
### Actual:

The Data Explorer is not visible until the user logs out and in. This goes for entity permissions as well.

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] Migration step added in case of breaking change
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by dennishendriksen** [comment]
@fdlk @sidohaakma could you add your notes from the phone call to this PR so that we don't forget about them when looking into this PR in the future (e.g. keycloak, worries regarding security vulnerabilities, spring deals with this for you)

**Comment by dennishendriksen** [comment]
@fdlk @sidohaakma *bump*

**Comment by fdlk** [comment]
We don't have notes from the phonecall but some considerations:

Existing behavior:
* For the release the bug to solve was smaller, namely that if the session auth roles are out of date (existing behavior) molgenis suddenly started showing error page (new bug, easy to fix)

Correctness:
* When we start a job in the user's name it runs with a security context not registered in the session registry and it will not get updated.
* When multiple threads finish adding roles (think e.g. a commander script that triggers quick successive role membership updates), you get nasty race conditions that mean the end result may be incorrect
* Adding nonstandard security code is tricky, may introduce vulnerabilities that we cannot oversee.

Heavily relies on existing session mechanism and existing architecture:
* JWTs can contain roles and by definition cannot be updated (signed and immutable, live in the client)

**Comment by dennishendriksen** [comment]
> When we start a job in the user's name it runs with a security context not registered in the session registry and it will not get updated.

This is not related to the issue reported in #4080. The fix in this PR shouldn't change the behavior for jobs.

> When multiple threads finish adding roles (think e.g. a commander script that triggers quick successive role membership updates), you get nasty race conditions that mean the end result may be incorrect

How to reproduce? Alternatively, can you point out which code change introduces the race conditions?

> Adding nonstandard security code is tricky, may introduce vulnerabilities that we cannot oversee.

I don't think this fix introduces non-standard security code. It is using code that we have been using in MOLGENIS for quiet some time with no known issues (keep in mind that #4080 is a regression). The existing code is based on solutions used by others to deal with the same issue.

> JWTs can contain roles and by definition cannot be updated (signed and immutable, live in the client)

MOLGENIS is not using any roles that might be stored in a JWT ...

File: molgenis-data-security/src/main/java/org/molgenis/data/security/SessionSecurityContextUpdaterImpl.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+      usernames.clear();
+    }
+  }
+
+  @Override
+  public void doCleanupAfterCompletion(String transactionId) {
+    actionThreadLocal.remove();
+  }
+
+  private void resetAuthorities(String username) {
```
Comment (fdlk) [inline molgenis-data-security/src/main/java/org/molgenis/data/security/SessionSecurityContextUpdaterImpl.java]: I think that this may overlap with concurrent updates to the authorities by other threads
