### PR TITLE
Fix #6803 When making a mistake editing the menu json it breaks the entire webapp

### LINKED ISSUE #6803: When making a mistake editing the menu json it breaks the entire webapp
### How to Reproduce
- edit the menu though the application settings
- remove or introduce some chars to create invalid json
### Expected behavior
an error is reported and the change is not saved

### Observed behavior
no error, settings are saved, upon reload (or navigation to any part of the application) I get a 500 page caused by freemarker

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
#### Checklist
- [ ] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

File: molgenis-core-ui/src/main/java/org/molgenis/ui/settings/AppDbSettings.java [hunk 1]
```diff
@@ -97,7 +97,8 @@ public void init()
 							  .setNillable(true)
 							  .setDefaultValue(getDefaultMenuValue())
 							  .setLabel("Menu")
-							  .setDescription("JSON object that describes menu content.");
+							  .setDescription("JSON object that describes menu content.")
+							  .setValidationExpression("$('" + MENU + "').isValidJson().value()");
```
Comment (fdlk) [inline molgenis-core-ui/src/main/java/org/molgenis/ui/settings/AppDbSettings.java]: Nice!
