### PR TITLE
Fix #5863 #5881 REST API v2 entity copy issues

### LINKED ISSUE #5863: Copy functionality does not work for users
### How to Reproduce
As admin import TypeTest
As user, with edit permissions on TypeTest, go to the dataexplorer
Press the copy button and name the entity UserCopy

### Expected behavior
A UserCopy entity is created

### Observed behavior
Error: Entity [it_emx_datatypes_UserCopy] does not exist

### PR DESCRIPTION
**Pull request by dennishendriksen**
Integration test not included, because pending on [M4721](http://www.molgenis.org/ticket/4721)

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/AggregateQueryGenerator.java [hunk 1]
```diff
@@ -46,11 +46,11 @@ public void generate(SearchRequestBuilder searchRequestBuilder, Attribute aggAtt
 		}
 		if (!aggAttr1.isAggregatable())
 		{
-			throw new IllegalArgumentException("Attribute is not isAggregatable [ " + aggAttr1.getName() + "]");
+			//			throw new IllegalArgumentException("Attribute is not isAggregatable [ " + aggAttr1.getName() + "]");
 		}
```
Comment (marikaris) [inline molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/AggregateQueryGenerator.java]: why did you put uncommented code in?

File: molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/AggregateQueryGenerator.java [hunk 2]
```diff
@@ -46,11 +46,11 @@ public void generate(SearchRequestBuilder searchRequestBuilder, Attribute aggAtt
...
 		if (aggAttr2 != null && !aggAttr2.isAggregatable())
 		{
-			throw new IllegalArgumentException("Attribute is not isAggregatable [ " + aggAttr2.getName() + "]");
+			//			throw new IllegalArgumentException("Attribute is not isAggregatable [ " + aggAttr2.getName() + "]");
```
Comment (marikaris) [inline molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/AggregateQueryGenerator.java]: why did you put uncommented code in?
