### PR TITLE
Fix #5888 Restarting application performs indexing actions

### LINKED ISSUE #5888: Restarting application performs indexing actions
### How to Reproduce
- Execute ```mvn jetty:run``` and wait until application bootstrapping are done
- Execute ```mvn jetty:stop``` and wait until application shutdown completes
- Execute ```mvn jetty:run``` and wait until application bootstrapping is done

### Expected behavior
- No indexing occurs at second startup because no data was modified

### Observed behavior
```
08:13:58.142 [main] INFO  o.m.bootstrap.MolgenisBootstrapper - Bootstrapping application ...
08:14:01.823 [main] INFO  o.m.bootstrap.MolgenisBootstrapper - Bootstrapping application completed
08:14:02.194 [pool-2-thread-1] INFO  o.m.data.jobs.model.JobExecution - Execution started.
08:14:02.211 [pool-2-thread-1] INFO  o.m.data.jobs.model.JobExecution - Start indexing for transaction id: [aaaacwvco6zmthfw2djjzsaaae]
08:14:02.252 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (0, Indexing sys_FileIngest)
08:14:02.531 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (1, Indexing sys_md_Attribute)
08:14:04.649 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (2, Indexing sys_md_Package)
08:14:05.376 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (3, Indexing sys_md_EntityType)
08:14:06.128 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (4, Indexing sys_set_directory)
08:14:06.555 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (5, Executed all index actions, cleaning up the actions...)
08:14:06.566 [pool-2-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (5, Cleaned up the actions.)
08:14:06.567 [pool-2-thread-1] INFO  o.m.data.jobs.model.JobExecution - Refresh index start
08:14:06.647 [pool-2-thread-1] INFO  o.m.data.jobs.model.JobExecution - Refresh index done
08:14:06.648 [pool-2-thread-1] INFO  o.m.data.jobs.model.JobExecution - Finished indexing for transaction id: [aaaacwvco6zmthfw2djjzsaaae]
08:14:06.697 [pool-2-thread-1] INFO  o.m.data.jobs.model.JobExecution - Execution successful. Time spent: 4s 453ms 
```

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [ ] Code reviewed
- [x] Code unit/integration/system tested
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java [hunk 1]
```diff
@@ -42,22 +43,27 @@
 {
 	private static final Logger LOG = LoggerFactory.getLogger(MetaDataServiceImpl.class);
 
+	private static final int BATCH_SIZE = 1000;
```
Comment (bartcharbon) [inline molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java]: This field is never used. PackagePersister has its own "BATCH_SIZE"

**Comment by bartcharbon** [comment]
test this please

**Comment by bartcharbon** [comment]
test this please
