### PR TITLE
Fix #4949 Settings filter is broken

### LINKED ISSUE #4949: Settings filter is broken (again!)
#### Reproduce
Log in as admin, go to the settings plugin, type a string into the search box

#### Expected
Settings options get filtered

#### Observed
Error message is displayed:
> Query with operator [LIKE] and data type [TEXT] not supported

Broken in master (tested on molgenis01)
Oddly enough: Works fine on 1.21.1 (tested on molgenis09)

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
The fix for #4910 causes issue #4949 
Might some slight changes to fix both issues.

## Note
It is not allowed to use multiple label attributes per entity!

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntityMetaData.java [hunk 1]
```diff
@@ -672,9 +672,14 @@ public void onChange(Package package_)
 	@Override
 	public AttributeMetaData getLabelAttribute(String languageCode)
 	{
-		String i18nLabelAttrName = getCachedAllAttrs().keySet().stream().filter(
-				attributeName -> attributeName.endsWith('-' + languageCode)).findFirst().orElse(null);
-		return i18nLabelAttrName != null ? getCachedAllAttrs().get(i18nLabelAttrName) : getLabelAttribute();
+		AttributeMetaData labelAttr = getLabelAttribute();
+		String labelAttributeName = labelAttr.getName();
+		if(labelAttributeName.endsWith("-en"))
```
Comment (bartcharbon) [inline molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntityMetaData.java]: use "-"+LanguageService.FALLBACK_LANGUAGE to prevent the functionality from breaking when we change the default language

File: molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntityMetaData.java [hunk 2]
```diff
@@ -672,9 +673,14 @@ public void onChange(Package package_)
 	@Override
 	public AttributeMetaData getLabelAttribute(String languageCode)
 	{
-		String i18nLabelAttrName = getCachedAllAttrs().keySet().stream().filter(
-				attributeName -> attributeName.endsWith('-' + languageCode)).findFirst().orElse(null);
-		return i18nLabelAttrName != null ? getCachedAllAttrs().get(i18nLabelAttrName) : getLabelAttribute();
+		AttributeMetaData labelAttr = getLabelAttribute();
+		String labelAttributeName = labelAttr.getName();
+		if(labelAttributeName.endsWith(FALLBACK_LANGUAGE))
```
Comment (bartcharbon) [inline molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntityMetaData.java]: You'll probably want to check for the "-" as a prefix as well

**Comment by bartcharbon** [comment]
test this please
