### PR TITLE
Fix #6545 When I type a space in the navigator, i receive an error message: {} 

### LINKED ISSUE #6545: When I type a space in the navigator, i receive an error message: {}
### How to Reproduce
Go to navigator
Type "indexing depth"

### Expected behavior
All tables matching "indexing depth"

### Observed behavior
screen shot 2017-08-22 at 09 09 31

### PR DESCRIPTION
**Pull request by sidohaakma**
#### Checklist
- [ ] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [x] Clean commits

### CODE REVIEW

**Comment by marikaris** [comment]
Should we write a test case/ update the test plan?

**Comment by marikaris** [comment]
Still breaks on ^

**Comment by marikaris** [comment]
When searching for: {} or '{}' or | or `
I still receive the error message: {}

File: molgenis-navigator/src/main/frontend/src/store/actions.js [hunk 1]
```diff
@@ -89,6 +89,24 @@ function queryPackages (query: string) {
   })
 }
 
+/**
+ *
+ * Validating specific input for searchbox
+ *
+ * @param query query to send to api/v2
+ */
+function validateQuery (query: string) {
```
Comment (marikaris) [inline molgenis-navigator/src/main/frontend/src/store/actions.js]: Can't this function be more generic? I like the clear error message but you never know what people might put in this query and if it is not in this function, they will still receive an error message like: {}

File: molgenis-navigator/src/main/frontend/test/unit/specs/components/Navigator.spec.js [hunk 2]
```diff
@@ -7,11 +7,11 @@ describe('Navigator', () => {
     })
   })
 
-  describe('submitQuery', () => {
-    it('should clear the query and dispatch a call to fetch all packages', () => {
+  describe('submitQueryWithSpecialCharacters', () => {
+    it('should clear the query and dispatch a call to fetch all packages with special characters', () => {
       Navigator.methods.$store = {
```
Comment (marikaris) [inline molgenis-navigator/src/main/frontend/test/unit/specs/components/Navigator.spec.js]: With the error messages for special characters I would really like to see a test, that checks if the correct error message is given.
