### PR TITLE
Fix #7917 Metadata manager lookup attribute doesn't work

### LINKED ISSUE #7917: Metadata manager lookup attribute doesn't work
### How to Reproduce
1) Go to Molgenis 101 . https://molgenis101.gcc.rug.nl/
2) Go to " meta datamanager)
3) Fill entity : Collections
4) Fill lookup attribute : 
      - collection name
      - collection acronym
      - biobank label
5) Click on safe
6) then refrese page. 

Now there are missing lookup attributes

### Expected behavior

In lookup attribute (collections)
      - collection name
      - collection acronym
      - biobank label

### Observed behavior

only biobank label

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
- Fix flow and lint error js files 
- Fix #7917 by using id equals instead of object equals
 
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java [hunk 1]
```diff
@@ -235,11 +235,19 @@ private Attribute toAttribute(
...
+    String editorAttributeId = editorAttribute.getId();
+    List<EditorAttributeIdentifier> lookupAttributes = editorEntityType.getLookupAttributes();
+
+    int index =
+        IntStream.range(0, lookupAttributes.size())
+            .map(idx -> lookupAttributes.get(idx).getId().equals(editorAttributeId) ? idx : -1)
+            .reduce(Integer::max)
+            .orElse(-1);
+
     return index != -1 ? index : null;
```
Comment (fdlk) [inline molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java]: I think you can do
```
int index = editorEntityType.getLookupAttributes()
        .stream()
        .map(EditorAttributeIdentifier::getId)
        .collect(toList())
        .indexOf(editorAttributeIdentifier.getId());
```
