### PR TITLE
Fix #5886 Fileingest running infinitely in case of missing mail settings

### LINKED ISSUE #5886: Fileingest running infinitely in case of missing mail settings
### How to Reproduce
- https://docs.google.com/spreadsheets/d/1KD2pw_h02i1If4o3ioZkxBdy8O9_g6PmxMg9onfOuoM/edit

and follow steps in tab File-ingester

### Expected behavior
- File ingest job fails with error indicating that mail could not be send

### Observed behavior
- File ingest job status is RUNNING

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [x] Clean commits

### CODE REVIEW

File: molgenis-jobs/src/test/java/org/molgenis/data/jobs/ProgressImplTest.java [hunk 1]
```diff
@@ -33,6 +38,7 @@
 	@BeforeMethod
 	public void beforeMethod()
 	{
+		MockitoAnnotations.initMocks(this);
```
Comment (dennishendriksen) [inline molgenis-jobs/src/test/java/org/molgenis/data/jobs/ProgressImplTest.java]: Mock initialization is already performed by parent class.

File: molgenis-util/src/test/java/org/molgenis/util/mail/MailSenderImplTest.java [hunk 2]
```diff
@@ -48,4 +48,11 @@ public void testSendTwoMessages()
 		mailSender.send(simpleMailMessage, secondSimpleMailMessage);
 		verify(actualMailSender).send(simpleMailMessage, secondSimpleMailMessage);
 	}
+
+	@Test(expectedExceptions = MailException.class)
+	public void failAtMailSenderConstruction()
+	{
+		doThrow(new IllegalStateException("fail!")).when(mailSenderFactory).createMailSender(mailSettings);
+		mailSender.send(simpleMailMessage);
```
Comment (ConnorStroomberg) [inline molgenis-util/src/test/java/org/molgenis/util/mail/MailSenderImplTest.java]: i dont think i understand , what is the use of this test , i looks like its testing a mocked call
