### PR TITLE
Fix #4593 GoNL annotator crashes on a certain SNV

### LINKED ISSUE #4593: GoNL annotator crashes on a certain SNV
When trying to annote a particular SNP with GoNL using CmdLineAnnotator 1.16.2 or 1.17.0, it crashes. Since it is early on in the file (chr 1) the problem will probably occur in other places too.

We try to annotate:
```
1       28227207        .       A       G
```

The line in the GoNL data:
```
1	28227207	.	ACT	A	.	PASS	AC=1;AN=996;GTC=497,1,0;set=INDEL
```

Error thrown:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1955)
	at org.molgenis.data.annotation.entity.impl.GoNLAnnotator$1.lambda$processQueryResults$19(GoNLAnnotator.java:139)
	at org.molgenis.data.annotation.entity.impl.GoNLAnnotator$1$$Lambda$39/2097905212.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.molgenis.data.annotation.entity.impl.GoNLAnnotator$1.processQueryResults(GoNLAnnotator.java:140)
	at org.molgenis.data.annotation.entity.impl.QueryAnnotatorImpl.annotateEntity(QueryAnnotatorImpl.java:106)
	at org.molgenis.data.annotation.entity.impl.QueryAnnotatorImpl.annotateEntity(QueryAnnotatorImpl.java:32)
	at org.molgenis.data.annotation.entity.impl.RepositoryAnnotatorImpl.annotateEntity(RepositoryAnnotatorImpl.java:53)
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:41)
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:18)
	at org.molgenis.data.annotation.cmd.CmdLineAnnotator.annotate(CmdLineAnnotator.java:268)
	at org.molgenis.data.annotation.cmd.CmdLineAnnotator.run(CmdLineAnnotator.java:151)
	at org.molgenis.data.annotation.cmd.CmdLineAnnotator.main(CmdLineAnnotator.java:174)
```

### PR DESCRIPTION
**Pull request by joerivandervelde**
Bugfix for GoNL annotator. Updated binary files with 1 extra variant for testing.

### CODE REVIEW

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/entity/impl/GoNLAnnotator.java [hunk 1]
```diff
@@ -128,15 +132,21 @@ else if (inputEntity.getString(VcfRepository.REF)
...
 						int postFixInputLength = resourceEntity.getString(VcfRepository.REF)
 								.substring(inputEntity.getString(VcfRepository.REF).length()).length();
+						//bugfix: matching A/G to ACT/A results in postFixInputLength=2, correctly updating ref from ACT to A,
+						//but then tries to substring the alt allele A to length -1 (1 minus 2) which is not allowed.
+						//added a check to prevent this: alt.length() > postFixInputLength ? trim the alt : change to 'n/a' because we cannot use this alt.
 						resourceEntity.set(VcfRepository.REF, resourceEntity.getString(VcfRepository.REF).substring(0,
 								(resourceEntity.getString(VcfRepository.REF).length() - postFixInputLength)));
 						String newAltString = Arrays.asList(resourceEntity.getString(ALT).split(",")).stream()
-								.map(alt -> alt.substring(0, (alt.length() - postFixInputLength)))
+								.map(alt -> alt.length() > postFixInputLength ? alt.substring(0, (alt.length() - postFixInputLength)) : "n/a")
```
Comment (fdlk) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/entity/impl/GoNLAnnotator.java]: I think I aaalmost understand what's going on even!
(is N/A the standard way to write this sort of thing in vcf, not . or whatever?)

Comment (joerivandervelde) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/entity/impl/GoNLAnnotator.java]: This is not supposed to be written back to VCF, only to facilitate the matching of non-obvious ref and alt alleles from a source VCF to a reference, such as GoNL.
