### PR TITLE
Revert "Fix #7528: As non-su I cannot import data"

### LINKED ISSUE #7528: As non-su I cannot import data
### How to Reproduce
- create a group "test"
- create a user "tester"
- add "tester" as a manager to group "test"
- try to import a entity without a package (e.g. attached file)

### Expected behavior
- after I select "add entities" I can select the "test" package to import to

### Observed behavior
- exception that I cannot read "sys" 
This is caused by the "isWritable" check, this will use the parent of a package to check for system packages, users have permission on amongst others "sys_beacon" but not on "sys"
Users should have COUNT on sys package

[mappingservice-test.xlsx](https://github.com/molgenis/molgenis/files/2180438/mappingservice-test.xlsx)

### PR DESCRIPTION
**Pull request by fdlk**
This reverts commit e1ec52d55dc2c3d43497609961d95f1b254bb7fe.
We already give the read meta permission to all users instead.

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java [hunk 1]
```diff
@@ -42,10 +41,7 @@ public static boolean isSystemPackage(@Nullable Package aPackage)
 		{
 			return false;
 		}
-		//Needs to run as system since you might not have permission to read the sys package
-		//Once we have READ_META permission checks on the packages this runAsSystem can be removed
-		//https://github.com/molgenis/molgenis/issues/7528
-		return runAsSystem(() -> aPackage.getId().equals(PACKAGE_SYSTEM) || (aPackage.getRootPackage() != null
-				&& aPackage.getRootPackage().getId().equals(PACKAGE_SYSTEM)));
+		return aPackage.getId().equals(PACKAGE_SYSTEM) || (aPackage.getRootPackage() != null
```
Comment (sidohaakma) [inline molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java]: Shouldn't this branch be tested in a JUnit test? There is also one for the EntityUtils class, but if you (as in the platform-team) have decided otherwise I could imagine this is not necessary.

**Comment by sidohaakma** [comment]
New Jenkins, works like a charm at this moment ;-D.

File: molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java (hunk 1 above)
Comment (fdlk) [reply molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java]: I’m juist reverting the RunAsSystem.
