### PR TITLE
Fix #8378 Importer ignores tags in the database, causing unjustified UnknownTagExceptions

### LINKED ISSUE #8378: Importer ignores tags in the database, causing unjustified UnknownTagExceptions
### How to Reproduce
Do NAVDOWN002 for the navigator:
Run the "testplan_navigator" script with mcmd
log in as nav_manager
Go to Navigator
click on package "nav"
select TypeTest
click the download icon
once the alert appears that your download is ready, click the link in the message to download the file
delete 'TypeTest'
import the file using the upload plugin

### Expected behavior
File imports and my typetest is back

### Observed behavior
Screen Shot 2019-04-08 at 09 55 43

### PR DESCRIPTION
**Pull request by bartcharbon**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [n.a.] (If you have changed REST API interface) view-swagger.ftl updated
- [n.a.] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java [hunk 1]
```diff
@@ -526,16 +526,18 @@ IntermediateParseResults parseSinglePackage(
...
       return emptyList();
     }
 
     List<Tag> tags = new ArrayList<>(tagIdentifiers.size());
     for (String tagIdentifier : tagIdentifiers) {
-      Tag tag = intermediateResults.getTag(tagIdentifier);
+      Tag tag =
+          intermediateResults.hasTag(tagIdentifier)
+              ? intermediateResults.getTag(tagIdentifier)
+              : dataService.findOneById(TAG, tagIdentifier, Tag.class);
```
Comment (dennishendriksen) [inline molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java]: Retrieving tags one-by-one is a potential performance issue. Consider determining which tags need to be retrieved via the data service and retrieve with a findAll.
