### PR TITLE
Fix #5533 Name [molgenis_annotated_thousand_genomes] too long during annotation

### LINKED ISSUE #5533: Name [molgenis_annotated_thousand_genomes] too long during annotation
#### Reproduce
- Extract https://molgenis26.gcc.rug.nl/downloads/annotators/annotation_resources.zip to <molgenis_home>/omx
- Download https://molgenis26.gcc.rug.nl/downloads/annotators/annotator_settings.xlsx and update paths to match resources on your system
- Import annotator_settings.xlsx using the 'Upload' plugin
- Unzip [corner_cases.zip](https://github.com/molgenis/molgenis/files/591459/corner_cases.zip) and import using the 'Upload' plugin
- Select entity 'corner_cases' in the 'Data explorer' plugin
- Select 'Annotators' tab (CGD, hpo, Gavin, OMIM should be listed as unavailable)
- Select 'Select all'
- Select 'Annotate'

#### Expected
- Annotation completes successfully

#### Observed
- ```org.molgenis.data.validation.MolgenisValidationException: Name [molgenis_annotated_thousand_genomes] is too long: maximum length is 30 characters.```
- Annotators that succeeded are not applied to data

### PR DESCRIPTION
**Pull request by tommydeboer**

### CODE REVIEW

File: molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/core/RepositoryAnnotator.java [hunk 1]
```diff
@@ -16,7 +16,7 @@
 
 public interface RepositoryAnnotator
 {
-	String ANNOTATOR_PREFIX = "molgenis_annotated_";
+	String ANNOTATOR_PREFIX = "annotated_";
```
Comment (Mark-de-Haan) [inline molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/core/RepositoryAnnotator.java]: I would use 'molgenis_', its more distinctive
