### PR TITLE
Fix #5985: Job logs can exceed max log size, disastrous consequences

### LINKED ISSUE #5985: Job logs can exceed max log size, disastrous consequences
### How to Reproduce
Use RD connect version of 3.0
Data in Marieke and Mariska RD connect folder on drive
Upload: RD connect model v20, diseases, tngb, ncl, bioner, ring14
Upload mappings (with new admin id)
Map to new entity

Molgenis 80 failed to run when this error occured during bootstrapping!

### Expected behavior
Mappings succeed without errors

### Observed behavior
Mapping succeeds but during indexing, the log keeps throwing this error message:
`' for attribute 'Log' of entity 'sys_idx_IndexJobExecution'.Value must be less than or equal to 65535 characters
	at org.molgenis.data.validation.RepositoryValidationDecorator.lambda$validate$0(RepositoryValidationDecorator.java:110) ~[molgenis-data-validation-3.0.0.jar:3.0.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_112]
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405) ~[na:1.8.0_112]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_112]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_112]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_112]
	at org.molgenis.data.validation.RepositoryValidationDecorator.update(RepositoryValidationDecorator.java:55) ~[molgenis-data-validation-3.0.0.jar:3.0.0]
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:131) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.RepositorySecurityDecorator.update(RepositorySecurityDecorator.java:128) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$update$11(TransactionalRepositoryDecorator.java:120) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.update(TransactionalRepositoryDecorator.java:118) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:131) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.support.DataServiceImpl.update(DataServiceImpl.java:121) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$2b061ccf.update(<generated>) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.tryUpdate(JobExecutionUpdaterImpl.java:40) [molgenis-jobs-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.lambda$updateInternal$1(JobExecutionUpdaterImpl.java:33) [molgenis-jobs-3.0.0.jar:3.0.0]
	at org.molgenis.security.core.runas.RunAsSystemProxy.lambda$runAsSystem$0(RunAsSystemProxy.java:47) ~[molgenis-security-core-3.0.0.jar:3.0.0]
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:61) ~[molgenis-security-core-3.0.0.jar:3.0.0]
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:45) ~[molgenis-security-core-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.updateInternal(JobExecutionUpdaterImpl.java:33) [molgenis-jobs-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.lambda$update$0(JobExecutionUpdaterImpl.java:28) [molgenis-jobs-3.0.0.jar:3.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_112]`

### PR DESCRIPTION
**Pull request by fdlk**
#### Checklist
- [ ] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] Clean commits

### CODE REVIEW

File: molgenis-jobs/src/test/java/org/molgenis/data/jobs/model/dummy/DummyJobExecutionEntityType.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+import org.molgenis.data.jobs.model.JobExecutionMetaData;
+import org.molgenis.data.meta.SystemEntityType;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Component;
+
+import static java.util.Objects.requireNonNull;
+import static org.molgenis.data.system.model.RootSystemPackage.PACKAGE_SYSTEM;
+
+@Component
+public class DummyJobExecutionEntityType extends SystemEntityType
```
Comment (tommydeboer) [inline molgenis-jobs/src/test/java/org/molgenis/data/jobs/model/dummy/DummyJobExecutionEntityType.java]: For consistency we should name it ```DummyJobExecutionMetadata```
