### PR TITLE
Fix #8018: System packages can be moved outside of system package

### LINKED ISSUE #8018: System packages can be moved outside of system package
### How to Reproduce
- Move a system package outside of the system package using e.g. the navigator plugin, the data explorer or the REST API

### Expected behavior
- Error stating that system metadata is not modifiable

### Observed behavior
- System package is moved outside of the system package

### PR DESCRIPTION
**Pull request by bartcharbon**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- User documentation updated
- (If you have changed REST API interface) view-swagger.ftl updated
- Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java [hunk 1]
```diff
@@ -41,16 +44,23 @@ public PackageRepositorySecurityDecorator(
   }
 
   @Override
-  public boolean isActionPermitted(Package pack, Action action) {
+  public boolean isActionPermitted(Package updatedPack, Action action) {
     boolean permitted;
+    Package currentPack = delegate().findOneById(updatedPack.getId());
+    if (action == CREATE || action == UPDATE || action == DELETE) {
+      if ((PackageUtils.isSystemPackage(updatedPack) || PackageUtils.isSystemPackage(currentPack))
```
Comment (tommydeboer) [inline molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java]: IntelliJ reports a warning here
