### PR TITLE
Fix #4119 UnknownEntityException when using getEntity() on an mref of a DefaultEntity

### LINKED ISSUE #4119: UnknownEntityException when using getEntity() on an mref of a DefaultEntity
When using ```getEntity()``` on an *mref* or *categorical mref* of a ```DefaultEntity``` you get an ```UnknownEntityException``` with the ID of the entity it couldn't find. This is confusing, because the entity does exist.

### PR DESCRIPTION
**Pull request by tommydeboer**

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java [hunk 1]
```diff
@@ -243,10 +244,18 @@ public Entity getEntity(String attributeName)
...
 		if (attribute == null) throw new UnknownAttributeException(attributeName);
 
-		if (value instanceof Map) return new DefaultEntity(attribute.getRefEntity(), dataService,
-				(Map<String, Object>) value);
+		if (value instanceof Map)
+			return new DefaultEntity(attribute.getRefEntity(), dataService, (Map<String, Object>) value);
 
-		value = attribute.getDataType().convert(value);
+		FieldType dataType = attribute.getDataType();
+		if (attribute.getDataType().equals(MolgenisFieldTypes.MREF)
```
Comment (dennishendriksen) [inline molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java]: attribute.getDataType() instanceof MrefField

File: molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java [hunk 2]
```diff
@@ -258,7 +267,8 @@ public Entity getEntity(String attributeName)
 	public <E extends Entity> E getEntity(String attributeName, Class<E> clazz)
 	{
 		Entity entity = getEntity(attributeName);
-		return entity != null ? new ConvertingIterable<E>(clazz, Arrays.asList(entity), dataService).iterator().next() : null;
```
Comment (dennishendriksen) [inline molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java]: Add unit test

File: molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java [hunk 3]
```diff
@@ -243,10 +244,18 @@ public Entity getEntity(String attributeName)
...
-				(Map<String, Object>) value);
+		if (value instanceof Map)
+			return new DefaultEntity(attribute.getRefEntity(), dataService, (Map<String, Object>) value);
 
-		value = attribute.getDataType().convert(value);
+		FieldType dataType = attribute.getDataType();
+		if (attribute.getDataType().equals(MolgenisFieldTypes.MREF)
+				|| attribute.getDataType().equals(MolgenisFieldTypes.CATEGORICAL_MREF))
+		{
+			throw new MolgenisDataException(
```
Comment (dennishendriksen) [inline molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java]: Add unit test

File: molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java [hunk 4]
```diff
@@ -243,10 +244,18 @@ public Entity getEntity(String attributeName)
...
+					"can't use getEntity() on an mref/categorical_mref, use getEntities() instead");
```
Comment (dennishendriksen) [inline molgenis-data/src/main/java/org/molgenis/data/support/DefaultEntity.java]: Include same check on getEntities when !attribute.getDataType() instanceof MrefField
