### PR TITLE
Fix #6583 Index queries fail when index doesn't exist (yet)

### LINKED ISSUE #6583: Index queries fail when index doesn't exist (yet)
### How to Reproduce
go to the dataexplorer
select index action
enter any "search" query in the "google search box" on the top left

### Expected behavior
search is preformed and matching rows, if any, are shown

### Observed behavior
Error! One or more indexes 'sysidxindexaction_43bbc99b' not found.

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [ ] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

File: molgenis-data-index/src/main/java/org/molgenis/data/index/IndexedRepositoryDecorator.java [hunk 1]
```diff
@@ -135,4 +158,89 @@ private boolean querySupported(Query<Entity> q)
...
+				return searchService.count(getEntityType(), q);
+			}
+			catch (UnknownIndexException e1)
+			{
+				throw translateUnknownIndexException();
+			}
+		}
+	}
+
+	private Object indexSearchOne(Query<Entity> q)
```
Comment (fdlk) [inline molgenis-data-index/src/main/java/org/molgenis/data/index/IndexedRepositoryDecorator.java]: The trying stuff twice can be put in single method (I've tried it out, will put up PR)

File: molgenis-data-index/src/main/java/org/molgenis/data/index/IndexedRepositoryDecorator.java [hunk 2]
```diff
@@ -135,4 +158,89 @@ private boolean querySupported(Query<Entity> q)
...
+				throw translateUnknownIndexException();
+			}
+		}
+	}
+
+	private void waitForIndexToBeStable()
+	{
+		try
+		{
+			indexJobScheduler.waitForIndexToBeStableIncludingReferences(getEntityType());
```
Comment (fdlk) [inline molgenis-data-index/src/main/java/org/molgenis/data/index/IndexedRepositoryDecorator.java]: This one used to be used in tests only, if we're going to use in production I think it's best to add a timeout. What do you think?

Comment (dennishendriksen) [reply molgenis-data-index/src/main/java/org/molgenis/data/index/IndexedRepositoryDecorator.java]: Its up to `waitForIndexToBeStableIncludingReferences` to interrupt after a certain amount of time. I propose to keep it like this and evaluate at the end of this sprint if and which changes are desired.
