### PR TITLE
Fix #5871 Importing EMX as non-superuser broken

### LINKED ISSUE #5871: Importing EMX as non-superuser broken
### How to Reproduce
- As non-superuser with plugin permission 'view' on 'importwizard' and 'dataexplorer' and entity class permission 'view' on 'sys_ImportRun' and 'sys_set_dataexplorer': extract [it_emx_datatypes.zip](https://github.com/molgenis/molgenis/files/810590/it_emx_datatypes.zip) and upload with default options using the 'Upload' plugin
- Navigate to 'Data explorer' plugin

### Expected behavior
- I can select 'TypeTest' in the entity dropdown
- As superuser: Selecting 'TypeTest' in the entity dropdown displays multiple inserted rows

### Observed behavior
- I cannot select 'TypeTest' in the entity dropdown
- As superuser: the data set contains zero rows

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested

### CODE REVIEW

File: molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java [hunk 1]
```diff
@@ -81,9 +80,9 @@
 		org.molgenis.data.RepositoryCollectionBootstrapper.class, org.molgenis.data.EntityFactoryRegistrar.class,
 		org.molgenis.data.importer.emx.EmxImportService.class, org.molgenis.data.importer.ImportServiceFactory.class,
 		org.molgenis.data.FileRepositoryCollectionFactory.class, org.molgenis.data.excel.ExcelDataConfig.class,
-		org.molgenis.security.permission.PermissionSystemService.class,
```
Comment (ConnorStroomberg) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java]: Why is this change needed ? , It is not really clean to me what the '@Import' annotation is needed for here.

Comment (dennishendriksen) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java]: The Import annotation value requires classes annotated with Configuration or regular component classes. Due to changes in the pull request PermissionSystemService is an interface and PermissionSystemServiceImpl is the component.

I suspect the Import annotation is used here to include specific components instead of including all components in its package which could result in dependency resolution issues.

File: molgenis-security/src/main/java/org/molgenis/security/permission/PermissionSystemServiceImpl.java [hunk 2]
```diff
@@ -20,79 +18,103 @@
...
 	{
-		this.dataService = requireNonNull(dataService);
+		this.userService = requireNonNull(userService);
 		this.userAuthorityFactory = requireNonNull(userAuthorityFactory);
+		this.roleHierarchy = requireNonNull(roleHierarchy);
+		this.dataService = requireNonNull(dataService);
+	}
+
+	@Override
+	public void giveUserEntityPermissions(EntityType entityType)
```
Comment (ConnorStroomberg) [inline molgenis-security/src/main/java/org/molgenis/security/permission/PermissionSystemServiceImpl.java]: maybe rename to something like 'giveUserWriteMetaPermissions' to hint at the fact Write_Meta permissions are given.

File: molgenis-security/src/main/java/org/molgenis/security/permission/PermissionSystemServiceImpl.java [hunk 3]
```diff
@@ -20,79 +18,103 @@
...
+	{
+		giveUserEntityPermissions(singleton(entityType));
 	}
 
 	@Override
-	public void giveUserEntityPermissions(Stream<EntityType> entityTypeStream)
+	public void giveUserEntityPermissions(Collection<EntityType> entityTypes)
```
Comment (ConnorStroomberg) [inline molgenis-security/src/main/java/org/molgenis/security/permission/PermissionSystemServiceImpl.java]: same comment as 'giveUserEntityPermissions'

**Comment by dennishendriksen** [comment]
Jenkins build encountered git fetch error, probably due to timeout

**Comment by dennishendriksen** [comment]
test this please

**Comment by ConnorStroomberg** [comment]
test this please
