### PR TITLE
[1.10] Fix #3764 TransactionLogService throws duplicate key exception

### LINKED ISSUE #3764: TransactionLogService throws duplicate key exception
The TransactionLogService.transactionStarted method does a dataService.add()

a) This add() method in the DataService is transactional and it shouldn't be. See #3737 .
b) When the transaction finishes, it does another add() which throws the duplicate key exception.

Sample logfile:
```
Exception in thread "Thread-11" org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO `MolgenisTransactionLog` (`transactionId`, `userName`, `startTime`, `transactionStatus`, `endTime`) VALUES (?, ?, ?, ?, ?)]; Duplicate entry 'aaaacuaffsxtklutac6ksryaae' for key 'PRIMARY'; nested exception is java.sql.BatchUpdateException: Duplicate entry 'aaaacuaffsxtklutac6ksryaae' for key 'PRIMARY'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:673)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:989)
	at org.molgenis.data.mysql.MysqlRepository.add(MysqlRepository.java:1109)
	at org.molgenis.data.mysql.MysqlRepository.add(MysqlRepository.java:1198)
	at org.molgenis.data.elasticsearch.ElasticsearchRepositoryDecorator.add(ElasticsearchRepositoryDecorator.java:38)
	at org.molgenis.data.transaction.TransactionLogRepositoryDecorator.add(TransactionLogRepositoryDecorator.java:190)
	at org.molgenis.util.IndexedRepositoryExceptionTranslatorDecorator.lambda$add$20(IndexedRepositoryExceptionTranslatorDecorator.java:156)
	at org.molgenis.util.SQLExceptionTranslatorTemplate.tryCatchSQLException(SQLExceptionTranslatorTemplate.java:20)
	at org.molgenis.util.IndexedRepositoryExceptionTranslatorDecorator.add(IndexedRepositoryExceptionTranslatorDecorator.java:155)
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:74)
	at org.molgenis.data.AutoValueRepositoryDecorator.add(AutoValueRepositoryDecorator.java:44)
	at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:148)
	at org.molgenis.data.transaction.AsyncTransactionLog$QueueConsumer.lambda$run$17(AsyncTransactionLog.java:83)
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:60)
	at org.molgenis.data.transaction.AsyncTransactionLog$QueueConsumer.run(AsyncTransactionLog.java:71)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: Duplicate entry 'aaaacuaffsxtklutac6ksryaae' for key 'PRIMARY'
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2055)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1467)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1723)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:1005)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:989)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
	... 16 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'aaaacuaffsxtklutac6ksryaae' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2441)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2007)
	... 21 more
```

### PR DESCRIPTION
**Pull request by erwinwinder**

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/data/transaction/AsyncTransactionLog.java [hunk 1]
```diff
@@ -78,7 +78,7 @@ public void run()
 						}
 						else if (type.equals(MolgenisTransactionLogMetaData.ENTITY_NAME))
 						{
-							dataService.getRepository(MolgenisTransactionLogMetaData.ENTITY_NAME).add(entity);
+							dataService.getRepository(MolgenisTransactionLogMetaData.ENTITY_NAME).update(entity);
```
Comment (fdlk) [inline molgenis-data/src/main/java/org/molgenis/data/transaction/AsyncTransactionLog.java]: Sometimes it really is that simple? :)
