### PR TITLE
Fix #7280 Importing multiple attributes with the same name doesn't throw an error

### LINKED ISSUE #7280: Importing multiple attributes with the same name doesn't throw an error
### How to Reproduce
Import: 
[Chr6_vragen_emx_testimport_12_everything_nillable.xlsx](https://github.com/molgenis/molgenis/files/1457455/Chr6_vragen_emx_testimport_12_everything_nillable.xlsx)
I merged here the three parts of the chromosome6 questionnaire and set everything nillable. It imported fine, so I was happy. Then we had the fix for the nillable expression and I got an error. It turned out I did merge everything, but did not delete the 2 additional id attributes. 

### Expected behavior
An error telling me to only use the name of every attribute once per entitytype

### Observed behavior
Everything imports fine and I have issues much later then one would expect.

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes
- [x] Integration tests run correctly

### CODE REVIEW

File: molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java [hunk 1]
```diff
@@ -463,6 +465,15 @@ public void testDoImportUpdateEmxAsSuperuser(File file, File updateFile, Map<Str
 				entityValidationMethod };
 	}
 
+	@Test(expectedExceptions = MolgenisDataException.class, expectedExceptionsMessageRegExp = "Duplicate attribute name [type] for entity type [it_emx_duplicateAttr]")
```
Comment (fdlk) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java]: escape the [], it's a regex
