### PR TITLE
Fix #6183 EntityType labels are allowed to consist of only white space or empty string

### LINKED ISSUE #6183: EntityType labels are allowed to consist of only white space or empty string
### How to Reproduce
Change the label of an entity to ' ' (space)

### Expected behavior
(Server-side) validation prevents this

### Observed behavior
Label is updated without error

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java [hunk 1]
```diff
@@ -290,6 +291,29 @@ private static void validateEntityName(EntityType entityType)
...
+	 * - Validates that the label is not an empty string
+	 * - Validates that the label does not only consist of white space
+	 *
+	 * @param entityType entity meta data
+	 * @throws MolgenisValidationException if the entity label is invalid
+	 */
+	private static void validateEntityLabel(EntityType entityType)
+	{
+		String label = entityType.getLabel();
+		if (label.isEmpty())
```
Comment (fdlk) [inline molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java]: I smell an incoming NPE here...
