### PR TITLE
M4691 As developer I want to get the date and datetime data types right so that I prevent DST bugs and allow users to specify exactly what they mean

### LINKED ISSUE #5845: When uploading a date, the date is displayed minus a day
### How to Reproduce
Upload the demo data: 
[very_advanced_data_example_v20170126.xlsx](https://github.com/molgenis/molgenis/files/796052/very_advanced_data_example_v20170126.xlsx)

Go to patients and look at date of death
In the EMX the date of death is for a number of patients 1998/05/02 (Fred Weasley for instance) and in the dataexplorer this date is 1998/05/01
### Expected behavior
1998/05/02 as date of death for Fred Weasley

### Observed behavior
1998/05/01 as date of death for Fred Weasley

### LINKED ISSUE #6066: EntityModelWriter treats DATE values as dateTime
### How to Reproduce
Let EntityModelWriter serialize a DATE attribute
(e.g. run testCreateRfdModelDATE unit test)

### Expected behavior
xml schema type is date and value shows only date value

### Observed behavior
(see expected value in unit test)
xml schema type is dateTime and value includes time value

### LINKED ISSUE #6103: Attribute conversion to and from DATE_TIME loses timezone information
### How to Reproduce
* Remove the //FIXME in DateTimeAttributeTypeUpdateTest.
* Add a validConversionData to StringAttributeTypeUpdateTest reading 
`{ "2016-11-13T20:20:20+0500", DATE_TIME, "2016-11-13T20:20:20+0500" }`

### Expected behavior
The cases work

### Observed behavior
The cases fail

### PR DESCRIPTION
**Pull request by fdlk**
Changes in this PR:
* In Entity class, switch from the current mix of `java.util.Date`, `java.sql.Date`, `java.sql.Timestamp` getters and setters to the java 8 time classes` java.time.Instant` (for DATE_TIME attributes) and `java.time.LocalDate` (for DATE attributes).
* Use system default time zone instead of fixed Europe/Amsterdam. You can specify the system default timezone using runtime property `-D user.timezone=Europe/Amsterdam` or by setting the `TZ` environment variable.
* Send dates to the client in UTC offset, format them there
* In PostgreSQL, switch DATE_TIME columns from TIMESTAMP to TIMESTAMP WITH TIME ZONE
   * Fixes #6103 Attribute conversion to and from DATE_TIME loses timezone information
* In Freemarker, use format() method on Instant and LocalDate
* Upgrade Apache POI from 3.9 to 3.15
* Fix #5845 When uploading a date, the date is displayed minus a day
* Fix #6066 EntityModelWriter serializes DATE values as dateTime
* Unit and integration tests now run in any timezone. I've done a successful build in timezone Hawaii.

The bugs fixed came out of inconsistent storage of date and datetime values.

##### Formatting
Use toString().
##### Parsing
For strict parsing, use Instant.parse() and LocalDate.parse().
For human provided strings, use loose parser to parse anything we can understand. Then interpret the result and process as needed to turn into Instant or LocalDate, whatever was requested.
If time zone information is missing but an Instant needs to be provided, interpret the LocalDate as a moment in the defaultZoneId().

#### Excel
The whole problem began probably because Excel stores dates without time zone but Apache POI turns numeric date-formatted cells into java.util.Date objects, interpreting them using the system default time zone.
* Upgrade POI so that you can do this conversion in UTC. 
* Format the interpreted strings as LocalDateTime because we still don't know the actual time zone they were supposed to be interpreted in.
> N.B. This only postpones the DST ambiguity to the moment where the local date time string is interpreted by the importer. When updating the importer, we should add an advanced feature that allows the user to specify their time zone.

#### JSON
Switch to ISO-8601 UTC in the JSON. This is system to system communication and the results should not be transformed into user space yet in JSON. Update the dataexplorer to format the dates using moment.js

#### Nashorn
We send a double to nashorn. Convert Instant to epoch millis. Interpret localdate in the default time zone.

#### PostgreSQL
For DATE_TIME attributes you can choose between TIMESTAMP and TIMESTAMP WITH TIME ZONE. The difference lies in the interpretation of string literals. Since we use JDBC the difference is next to nothing. JDBC [allows you to use java 8 time classes](https://jdbc.postgresql.org/documentation/head/8-date-time.html) so we'll switch to those for the query values and entity values and row mapping.

BUT when converting an attribute from STRING to DATE_TIME, we currently lose the timestamp stored in the string cause PostgreSQL ignores the time zone part of the string.
This is bug #6103. Fixed it by switching to TIMESTAMP WITH TIME ZONE.

#### Freemarker
Freemarker doesn't support the java.time datatypes out of the box.
Found a set of Java 8 formatters that allow you to customize the formatting of java 8 time classes.
In .ftl files, move from ?date_time to .format() with optional format string.

#### Checklist
- [x] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-charts/src/main/java/org/molgenis/charts/highcharts/convert/HighchartSeriesUtil.java [hunk 1]
```diff
@@ -137,45 +142,4 @@ else if (AttributeType.DATE.equals(fieldTypeEnum))
...
-	 */
-	public Long convertDateToMilliseconds(Date date)
-	{
-		if (date == null) return null;
-		Calendar calendar = Calendar.getInstance();
-		calendar.setTime(date);
-		Calendar calendarConverted = Calendar.getInstance(TimeZone.getTimeZone("GMT"), Locale.ENGLISH);
-		calendarConverted.clear();
-		calendarConverted.set(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DATE));
-		return calendarConverted.getTimeInMillis();
```
Comment (fdlk) [inline molgenis-charts/src/main/java/org/molgenis/charts/highcharts/convert/HighchartSeriesUtil.java]: This code is a symptom of the problem. A java.util.Date is a wrapper around a long and represents a moment in time. If you use java.util.Date to store a local date without time, you need to convert the local date to a moment in time. High charts expects a date value to be transferred as epoch millis on the moment that that the day of that date starts in UTC. But molgenis internally used time zone Europe/Amsterdam. Here we convert from the one timezone to the other. Now that we use Instant molgenis-wide, we can simply turn the Instant into epoch millis and be done with it.

File: molgenis-core-ui/src/main/javascript/modules/react-components/Table.js [hunk 2]
```diff
@@ -809,6 +810,12 @@ var TableCellContent = React.createClass({
                         )
                     );
                     break;
+                case 'DATE':
+                    CellContent = span(null, moment(value).format('ll'));
+                    break;
+                case 'DATE_TIME':
+                    CellContent = span(null, moment(value).format('lll'));
```
Comment (fdlk) [inline molgenis-core-ui/src/main/javascript/modules/react-components/Table.js]: Send UTC dates to the client and format them over there.

File: molgenis-core/src/main/java/org/molgenis/util/MolgenisDateFormat.java [hunk 3]
```diff
@@ -1,36 +1,117 @@
...
+import java.time.format.DateTimeParseException;
+import java.time.temporal.TemporalAccessor;
 import java.util.TimeZone;
 
-import static java.lang.String.format;
-
 public class MolgenisDateFormat
 {
-	// TODO FIXME Do system default!
+	// TODO FIXME Switch to system default
```
Comment (fdlk) [inline molgenis-core/src/main/java/org/molgenis/util/MolgenisDateFormat.java]: This is now really a matter of preference, we can pick whatever we like.

File: molgenis-core/src/test/java/org/molgenis/util/MolgenisDateFormatTest.java [hunk 4]
```diff
@@ -1,20 +1,63 @@
...
+	}
+
+	@DataProvider(name = "parseInstantDataProvider")
+	public Object[][] parseInstantDataProvider()
+	{
+		return new Object[][] { { "2000-12-31T12:34:56.789+0200", "2000-12-31T10:34:56.789Z" },
+				{ "2000-12-31T12:34:56.789+02:00", "2000-12-31T10:34:56.789Z" },
+				{ "2000-12-31T12:34:56.789", "2000-12-31T11:34:56.789Z" },
+				{ "2000-12-31T12:34", "2000-12-31T11:34:00Z" }, { "2000-12-31T12:34Z", "2000-12-31T12:34:00Z" },
+				{ "2000-12-31", "2000-12-30T23:00:00Z" }, };
```
Comment (fdlk) [inline molgenis-core/src/test/java/org/molgenis/util/MolgenisDateFormatTest.java]: This last one's the most interesting one. We interpret incomplete date time strings as the start of date in the system's default time zone.

File: molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelUtils.java [hunk 5]
```diff
@@ -4,36 +4,50 @@
...
 		return toValue(cell, null);
 	}
 
 	// Gets a cell value as String and process the value with the given cellProcessors
-	public static String toValue(Cell cell, List<CellProcessor> cellProcessors)
+	static String toValue(Cell cell, List<CellProcessor> cellProcessors)
 	{
 		String value;
-		switch (cell.getCellType())
+		switch (cell.getCellTypeEnum())
```
Comment (fdlk) [inline molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelUtils.java]: new version of apache poi deprecated the int constants and switched to enum

File: molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/AttributeValidatorTest.java [hunk 6]
```diff
@@ -151,15 +151,16 @@ public void testDefaultValueDate()
...
+					"Text 'test' could not be parsed, unparsed text found at index 0");
 		}
 	}
 
 	@Test
 	public void testDefaultValueDateValid()
 	{
 		Attribute attr = mock(Attribute.class);
-		when(attr.getDefaultValue()).thenReturn("01-01-2016");
+		when(attr.getDefaultValue()).thenReturn("2016-01-01");
```
Comment (fdlk) [inline molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/AttributeValidatorTest.java]: whoops, that was a bit too lenient of our parser!

File: molgenis-data/src/main/java/org/molgenis/data/populate/AutoValuePopulator.java [hunk 7]
```diff
@@ -75,12 +74,10 @@ private static void generateAutoDateOrDateTime(Iterable<? extends Entity> entiti
 				switch (type)
 				{
 					case DATE:
-						Date localDateUTC = Date.from(LocalDate.now().atStartOfDay(ZoneId.of("UTC")).toInstant());
-						entity.set(attr.getName(), localDateUTC);
+						entity.set(attr.getName(), LocalDate.now(getDefaultZoneId()));
```
Comment (fdlk) [inline molgenis-data/src/main/java/org/molgenis/data/populate/AutoValuePopulator.java]: The current date depends on where you are!

File: molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/datatypeediting/StringAttributeTypeUpdateTest.java [hunk 8]
```diff
@@ -42,7 +42,8 @@ public void afterClass()
 				{ "A VERY LONG TEXT!!!!@#$#{@}{@}{#%$#*($&@#", TEXT, "A VERY LONG TEXT!!!!@#$#{@}{@}{#%$#*($&@#" },
 				{ "1", ENUM, "1" }, { "<h1>Hello World</h1>", HTML, "<h1>Hello World</h1>" },
 				{ "Compounds go!", COMPOUND, null }, { "1990-11-13", DATE, "1990-11-13" },
-				{ "2016-11-13T20:20:20+0100", DATE_TIME, "2016-11-13T20:20:20+0100" } };
+				{ "2016-11-13T20:20:20+0100", DATE_TIME, "2016-11-13T20:20:20+0100" },
+				{ "2016-11-13T20:20:20+0500", DATE_TIME, "2016-11-13T20:20:20+0500" } };
```
Comment (fdlk) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/datatypeediting/StringAttributeTypeUpdateTest.java]: Fixes bug, this used to pick system default time zone for all datetime strings when converting to date_time

**Comment by marikaris** [comment]
#5824 is indeed back as far as I can see 
screen shot 2017-04-18 at 12 57 28
using this algorithm: 
`if($('date_of_death').value()){
   var date = $('date_of_death').value().split('-')
   new Date(date[0], date[1], date[2])
}`
and this also:
`if($('date_of_death').value()){
   var date = $('date_of_death').value()
   new Date(date)
}`

File: molgenis-fair/src/test/java/org/molgenis/fair/controller/EntityModelWriterTest.java [hunk 9]
```diff
@@ -243,9 +240,8 @@ public void testCreateRfdModelDATE()
 
 		assertEquals(result.size(), 1);
 		Iterator results = result.iterator();
-		//TODO: This test documents bug #6066, fix it!
 		assertEquals(results.next().toString(),
-				"(http://molgenis01.gcc.rug.nl/fdp/catolog/test/this, http://IRI.nl, \"2013-08-12T00:00:00.000+02:00\"^^<http://www.w3.org/2001/XMLSchema#dateTime>) [null]");
+				"(http://molgenis01.gcc.rug.nl/fdp/catolog/test/this, http://IRI.nl, \"2013-08-12\"^^<http://www.w3.org/2001/XMLSchema#date>) [null]");
```
Comment (fdlk) [inline molgenis-fair/src/test/java/org/molgenis/fair/controller/EntityModelWriterTest.java]: Fixes #6066

File: molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/datatypeediting/DateTimeAttributeTypeUpdateTest.java [hunk 10]
```diff
@@ -55,14 +57,14 @@ public void afterClass()
 	 * @param convertedValue  The expected value after converting the type
 	 * @throws ParseException
 	 */
-	// FIXME @Test(dataProvider = "validConversionTestCases")
```
Comment (fdlk) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/datatypeediting/DateTimeAttributeTypeUpdateTest.java]: Fixed!

File: molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java [hunk 11]
```diff
@@ -594,8 +593,7 @@ public void testDoImportUpdateEmxAsSuperuser(File file, File updateFile, Map<Str
 	static
 	{
 		testXref1FirstRow.put("Identifier", "xref_1");
-		testXref1FirstRow.put("Date_1", Date.from(LocalDate.of(2013, 12, 10).atStartOfDay(UTC)
-				.toInstant())); // FIXME should be 11th (https://github.com/molgenis/molgenis/issues/5845)
```
Comment (fdlk) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java]: Fixed

File: molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java [hunk 12]
```diff
@@ -604,8 +602,7 @@ public void testDoImportUpdateEmxAsSuperuser(File file, File updateFile, Map<Str
 	static
 	{
 		testXref1LastRow.put("Identifier", "xref_50");
-		testXref1LastRow.put("Date_1", Date.from(LocalDate.of(2001, 2, 13).atStartOfDay(UTC)
-				.toInstant())); // FIXME should be 14th (https://github.com/molgenis/molgenis/issues/5845)
```
Comment (fdlk) [inline molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java]: Fixed!

File: molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/QueryGenerator.java [hunk 13]
```diff
@@ -888,18 +888,31 @@ private Object getQueryValue(Attribute attribute, Object queryRuleValue)
...
 				}
 				else if (queryRuleValue instanceof String)
 				{
 					return queryRuleValue;
 				}
 				else
 				{
-					throw new MolgenisQueryException(format("Query value must be of type Date instead of [%s]",
+					throw new MolgenisQueryException(format("Query value must be of type Instant instead of [%s]",
 							queryRuleValue.getClass().getSimpleName()));
```
Comment (mswertz) [inline molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/QueryGenerator.java]: Will error also be posted to end user? Because then I think 'Instant' is not very informational. Instead provide info on how Instant should be formatted?

File: molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java [hunk 14]
```diff
@@ -150,10 +152,10 @@ public RestControllerV2(DataService dataService, MolgenisPermissionService permi
...
 		if (molgenisVersion == null) throw new IllegalArgumentException("molgenisVersion is null");
 		if (molgenisBuildDate == null) throw new IllegalArgumentException("molgenisBuildDate is null");
-		molgenisBuildDate = molgenisBuildDate.equals("${maven.build.timestamp}") ?
-				new SimpleDateFormat("yyyy-MM-dd HH:mm").format(new java.util.Date())
-						+ " by IntelliJ" : molgenisBuildDate;
-
+		if (molgenisBuildDate.equals("${maven.build.timestamp}"))
+		{
+			molgenisBuildDate = DateTimeFormatter.ofLocalizedDateTime(MEDIUM).format(now()) + " by IntelliJ";
+		}
```
Comment (mswertz) [inline molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java]: What is this?

**Comment by mswertz** [comment]
What is default setting if -d property is not given and env not set. I suppose Amsterdam?

File: molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java (hunk 14 above)
Comment (fdlk) [inline molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java]: An existing workaround to show some kind of build timestamp when IntelliJ rather than maven has built the code. This updates it to java 8 time classes.

File: molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/QueryGenerator.java (hunk 13 above)
Comment (fdlk) [inline molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/QueryGenerator.java]: This particular message is a programming bug if it occurs. In some other places where we parse user input, the current message says "Couldn't be parsed as a date" or "Couldn't be parsed as a datetime". I'll update to add one specific format that's allowed.

**Comment by fdlk** [comment]
Default setting gets picked up from the OS and depends on the OS. Our vm's appear to be configured to Europe/Amsterdam.
> molgenis@molgenis09 ~> date
Tue Apr 25 10:41:07 CEST 2017

File: molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/QueryGenerator.java (hunk 13 above)
Comment (fdlk) [inline molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/request/QueryGenerator.java]: Updated
