### PR TITLE
Fix #5711 User repository decorator delete issues 

### LINKED ISSUE #5711: User repository decorator delete issues
### How to Reproduce
- Delete a superuser through the REST API or data explorer plugin
- Delete a non-superuser through the REST API or data explorer plugin

### Expected behavior
- User authorities for the user are removed

### Observed behavior
- User authorities are not removed

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [x] Unit tests

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/auth/UserRepositoryDecorator.java [hunk 1]
```diff
@@ -129,20 +132,70 @@ private void updateSuperuserAuthority(User user)
...
+				.findAll(GROUP_MEMBER, new QueryImpl<GroupMember>().eq(GroupMemberMetaData.USER, user),
+						GroupMember.class);
+		dataService.delete(GROUP_MEMBER, groupMembers);
+	}
+
+	@Override
+	public void deleteAll()
 	{
-		return dataService.getRepository(USER_AUTHORITY, UserAuthority.class);
+		throw new UnsupportedOperationException("Deleting all users is not supported.");
```
Comment (fdlk) [inline molgenis-data/src/main/java/org/molgenis/auth/UserRepositoryDecorator.java]: awwwh! :D

**Comment by fdlk** [comment]
test this please
