### PR TITLE
Fix #4289 ResourceUtils - NullPointerException is thrown

### LINKED ISSUE #4289: ResourceUtils - NullPointerException is thrown
14:28:32.088 [ajp-bio-8009-exec-4] ERROR org.molgenis.util.ResourceUtils - NullPointerException is thrown. Resource url: jar:file:/srv/molgenis/apache-tomcat-7.0.65/webapps/ROOT/WEB-INF/lib/molgenis-core-ui-1.15.0-SNAPSHOT.jar!/i18n.xlsx
14:28:32.101 [ajp-bio-8009-exec-4] ERROR o.s.web.context.ContextLoader - Context initialization failed
java.lang.RuntimeException: java.lang.NullPointerException
	at org.molgenis.util.ResourceUtils.getFile(ResourceUtils.java:85) ~[molgenis-core-1.15.0-SNAPSHOT.jar:1.15.0-SNAPSHOT]
	at org.molgenis.util.ResourceUtils.getFile(ResourceUtils.java:27) ~[molgenis-core-1.15.0-SNAPSHOT.jar:1.15.0-SNAPSHOT]
	at org.molgenis.ui.I18nStringsPopulator.onApplicationEvent(I18nStringsPopulator.java:49) ~[molgenis-core-ui-1.15.0-SNAPSHOT.jar:1.15.0-SNAPSHOT]
	at org.molgenis.ui.I18nStringsPopulator.onApplicationEvent(I18nStringsPopulator.java:28) ~[molgenis-core-ui-1.15.0-SNAPSHOT.jar:1.15.0-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:775) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434) ~[spring-web-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5001) [catalina.jar:7.0.65]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517) [catalina.jar:7.0.65]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.65]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.65]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.65]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.65]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095) [catalina.jar:7.0.65]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:558) [catalina.jar:7.0.65]
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1747) [catalina.jar:7.0.65]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301) [tomcat-coyote.jar:7.0.65]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_31]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_31]
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1516) [catalina.jar:7.0.65]
	at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:739) [catalina.jar:7.0.65]
	at org.apache.catalina.manager.ManagerServlet.doPut(ManagerServlet.java:457) [catalina.jar:7.0.65]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:653) [servlet-api.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.65]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.65]
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108) [catalina.jar:7.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.65]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.65]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.65]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.65]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614) [catalina.jar:7.0.65]
	at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:334) [catalina.jar:7.0.65]
	at org.apache.catalina.valves.RemoteAddrValve.invoke(RemoteAddrValve.java:119) [catalina.jar:7.0.65]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.65]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.65]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) [catalina.jar:7.0.65]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.65]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) [catalina.jar:7.0.65]
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190) [tomcat-coyote.jar:7.0.65]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) [tomcat-coyote.jar:7.0.65]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote.jar:7.0.65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277) ~[na:1.8.0_31]
	at org.molgenis.util.ResourceUtils.getFile(ResourceUtils.java:76) ~[molgenis-core-1.15.0-SNAPSHOT.jar:1.15.0-SNAPSHOT]
	... 57 common frames omitted

### PR DESCRIPTION
**Pull request by jjettenn**

### CODE REVIEW

File: molgenis-core-ui/src/main/java/org/molgenis/ui/I18nStringsPopulator.java [hunk 1]
```diff
@@ -46,7 +47,7 @@ public void onApplicationEvent(ContextRefreshedEvent event)
 	{
 		LOG.info("Importing i18n strings...");
 
-		File file = ResourceUtils.getFile("i18n.xlsx");
+		File file = new File(Resources.getResource("i18n.xlsx").getPath());
```
Comment (fdlk) [inline molgenis-core-ui/src/main/java/org/molgenis/ui/I18nStringsPopulator.java]: Still doesn't work, I've reopened the issue and added the log. I think you cannot instantiate a FileRepositoryCollection on top of a resource, probably?
