### PR TITLE
Fix #6109 & #6226 Delete package issues

### LINKED ISSUE #6109: Error deleting somewhat complicated package structure
### How to Reproduce
As admin
* Upload 
[very_advanced_data_example_v20170126.xlsx](https://github.com/molgenis/molgenis/files/951252/very_advanced_data_example_v20170126-2.xlsx) in a clean molgenis, use mode ADD and default options.
* Go to Data Explorer, select Package entity
* Delete root package

### Expected behavior
Everything is gone

Everything is still there.

### PR DESCRIPTION
**Pull request by tommydeboer**
#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java [hunk 1]
```diff
@@ -251,7 +251,7 @@ public void delete(EntityType entity)
 	@Override
 	public void delete(Stream<EntityType> entities)
 	{
-		super.update(entities.filter(entityType ->
+		super.delete(entities.filter(entityType ->
```
Comment (fdlk) [inline molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java]: whoops! :)

**Comment by tommydeboer** [comment]
You're still getting the error because you're removing a package which has entities in it that are referenced from outside the package. Deleting the 'root' package should be possible now (where it wasn't before).

I agree that the error message isn't all too clear but it's coming straight from the ```PostgresqlExceptionTranslator```. Do you have any suggestions on how to create a better message?
