### PR TITLE
Fix #6325 "Unknown table name" when deleting EntityType with references to it

### LINKED ISSUE #6325: "Unknown table name" when deleting EntityType with references to it
### How to Reproduce
1. Import *it_emx_datatypes*
2. In the data explorer, go to TypeTestRef
3. Deleta meta + metadata

### Expected behavior
Error messages that says the entity can't be deleted because it is referenced by TypeTest

### Observed behavior
```Error! Unknown entity for table name [it_emx_datatypes_TypeT#8a25d662_xcategoricalmref_value]```

After deleting TypeTest, TypeTestRef can be deleted again

### PR DESCRIPTION
**Pull request by tommydeboer**
Stores junction table names in the EntityTypeRegistry as well, so that the corresponding EntityType can be looked up even when the generated id is long and truncated. 

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits

### CODE REVIEW

File: molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/identifier/EntityTypeRegistryImplTest.java [hunk 1]
```diff
@@ -47,15 +50,46 @@ public void testGetEntityTypeDescription() throws Exception
...
-		when(entityType.getAllAttributes()).thenReturn(emptyList());
-		when(entityType.getId()).thenReturn(entityTypeId);
+		EntityType entityType = prepareMockEntityTypeForRegistering();
+
 		entityTypeRegistryImpl.registerEntityType(entityType);
-		String tableName = "entityTypeId#c34894ba_mrefattr";
-		assertEquals(entityTypeRegistryImpl.getEntityTypeDescription(tableName),
-				EntityTypeDescription.create(entityTypeId, ImmutableMap.of()));
+
+		assertNotNull(entityTypeRegistryImpl.getEntityTypeDescription("org_molgenis_test_many_packages_deep#2409e1c6"));
```
Comment (fdlk) [inline molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/identifier/EntityTypeRegistryImplTest.java]: Probably a bit crisper to check that the entity type id in the EntityTypeDescription is correct?
