### PR TITLE
Fix #7498 Mappings between molgenis 6 and 7 not compatible

### LINKED ISSUE #7498: Mappings between molgenis 6 and 7 not compatible
### How to Reproduce
Upload: 
[lifelines_demo.xlsx](https://github.com/molgenis/molgenis/files/2149433/lifelines_demo.xlsx)
 and: 
[lifelines_demo_patient_target.xlsx](https://github.com/molgenis/molgenis/files/2149434/lifelines_demo_patient_target.xlsx)
create mapping, map to target patient, use questionnaire as source
create mapping for attribute: Abnormality of skull size
algorithm:
```javascript
if($('Abnormality_of_skull_size').value() === 'y'){
    true;
}else{
    false;
}
```
Validate
### Expected behavior
if yes, the mapping will return true

### Observed behavior
everything is false, i should use:

```javascript
if($('Abnormality_of_skull_size').value().id === 'y'){
    true;
}else{
    false;
}
```

### PR DESCRIPTION
**Pull request by tommydeboer**
When merging, please also look at https://github.com/molgenis/magma-script-js/pull/3

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] (If you have changed REST API interface) view-swagger.ftl updated
- [x] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

**Comment by dennishendriksen** [comment]
Can you update the expressions user documentation?

File: molgenis-js/src/main/resources/js/script-evaluator.js [hunk 1]
```diff
@@ -6,22 +6,22 @@
...
 function evalScript (script, entity) {
-    // make functions available to the script in local scope
-    // noinspection JSUnusedLocalSymbols
-    var $ = MagmaScript.$.bind(entity) //NOSONAR
-    // noinspection JSUnusedLocalSymbols
-    var newValue = MagmaScript.newValue // NOSONAR
-    // noinspection JSUnusedLocalSymbols
-    var _isNull = MagmaScript._isNull // NOSONAR
-    return eval(script)
+  // make functions available to the script in local scope
```
Comment (dennishendriksen) [inline molgenis-js/src/main/resources/js/script-evaluator.js]: Was the previous formatting incorrect? Or is your formatting incorrect?

Comment (tommydeboer) [reply molgenis-js/src/main/resources/js/script-evaluator.js]: The previous formatting was incorrect.
