### PR TITLE
Fix #5329 VCF invalid due to missing "." for multi-allelic missing values

### LINKED ISSUE #5329: VCF output invalid due to missing "." for multi-allelic missing values
Multi allelic values with annotations may be read in like this:

```
1   54728   .   G   T,C .   .   GoNL_AF=0.01,.;CADD_SCALED=34.0,.;
```

Where GoNL and CADD annotations for the 'C' allele are missing.

But the VCF writer outputs is as:

```
1   54728   .   G   T,C .   .   GoNL_AF=0.01,;CADD_SCALED=34.0,;
```

Which is NOT valid VCF, and loading this file with VCF reader will fail because only 1 value is seen.

Note that this only happens when values are typed correctly (as Float). Then they are parsed as "Object val = [34.0, null]" where String values are parsed as "Object val = [0.01, .]".

### PR DESCRIPTION
**Pull request by dennishendriksen**
Update Genotype-IO 1.0.1 to 1.0.3

#### Checklist
- [ ] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] (If you have changed REST API interface) view-swagger.ftl updated
- [ ] Test plan template updated
- [ ] Clean commits

### CODE REVIEW

File: molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/format/VcfToEntity.java [hunk 1]
```diff
@@ -363,8 +363,11 @@ private void writeInfoFieldsToEntity(VcfRecord vcfRecord, Entity entity)
 				}
 				else if (vcfInfoVal instanceof List<?>)
 				{
+					List<?> vcfInfoValTokens = (List<?>) vcfInfoVal;
 					// TODO Use list data type once available (see http://www.molgenis.org/ticket/2681)
```
Comment (ConnorStroomberg) [inline molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/format/VcfToEntity.java]: is this todo still relevant ?

Comment (dennishendriksen) [inline molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/format/VcfToEntity.java]: Yes
