### PR TITLE
Fix #8675 Various performance improvements

### LINKED ISSUE #8675: Importing pointing study data slow
### How to Reproduce
Import an emx csv.zip containing data plus metadata for a nontrivial model like bbmri eric or the pointing study. I think what they have in common is a lot of small code lists.

### Expected behavior
It works

### Observed behavior
I do not have the patience to wait it out. Does not look like it will ever finish.
If you split it into two files, one for metadata and one for data, metadata takes a while but can be imported and data finishes near instantly

### PR DESCRIPTION
**Pull request by dennishendriksen**
#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [NA] Migration step added in case of breaking change
- [NA] User documentation updated
- [NA] (If you have changed REST API interface) view-swagger.ftl updated
- [NA] Test plan template updated
- [x] Clean commits
- [x] Added Feature/Fix to release notes

### CODE REVIEW

File: molgenis-data/src/main/java/org/molgenis/data/Fetch.java [hunk 1]
```diff
@@ -19,10 +20,22 @@
...
+    this(false);
+  }
+
+  /**
+   * Creates an empty valid Fetch. Can be used to improve performance in case of system entity type
+   * fetches defined by the system.
+   *
+   * @param validated whether or not the fetch has been validated
+   */
+  public Fetch(boolean validated) {
```
Comment (tommydeboer) [inline molgenis-data/src/main/java/org/molgenis/data/Fetch.java]: For clarity it's a bit nicer to make this one private and use a factory method instead.
